// Mock Services Data with Indian context
export const mockServices = [
  {
    id: 'SVC-0001',
    code: 'CON-0001',
    name: 'General Physician Consultation',
    description: 'Initial consultation with general physician including basic examination and prescription',
    category: 'consultation',
    department: 'general',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 15,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 1250,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-20'),
    notes: 'Most common service, high volume',
  },
  {
    id: 'SVC-0002',
    code: 'CON-0002',
    name: 'Specialist Consultation - Cardiology',
    description: 'Consultation with cardiologist including ECG review and treatment planning',
    category: 'consultation',
    department: 'cardiology',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 1500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 30,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 420,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-18'),
    notes: '',
  },
  {
    id: 'SVC-0003',
    code: 'CON-0003',
    name: 'Follow-up Consultation',
    description: 'Follow-up visit for treatment review and progress check',
    category: 'consultation',
    department: 'general',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 300,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 10,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'partial',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 890,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-19'),
    notes: '',
  },
  {
    id: 'SVC-0004',
    code: 'LAB-0001',
    name: 'Complete Blood Count (CBC)',
    description: 'Full blood count analysis including RBC, WBC, platelets, hemoglobin, and indices',
    category: 'laboratory',
    department: 'pathology',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 350,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 2,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 2100,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Report available in 2-4 hours',
  },
  {
    id: 'SVC-0005',
    code: 'LAB-0002',
    name: 'Lipid Profile',
    description: 'Complete lipid panel - Total cholesterol, HDL, LDL, VLDL, Triglycerides',
    category: 'laboratory',
    department: 'pathology',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 600,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 4,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 780,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-21'),
    notes: 'Fasting required 10-12 hours',
  },
  {
    id: 'SVC-0006',
    code: 'LAB-0003',
    name: 'Thyroid Profile (T3, T4, TSH)',
    description: 'Complete thyroid function test including T3, T4, and TSH levels',
    category: 'laboratory',
    department: 'pathology',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 800,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 6,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 560,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-20'),
    notes: '',
  },
  {
    id: 'SVC-0007',
    code: 'LAB-0004',
    name: 'HbA1c (Glycated Hemoglobin)',
    description: 'Diabetes monitoring test - 3-month average blood sugar levels',
    category: 'laboratory',
    department: 'pathology',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 550,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 4,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 920,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-20'),
    notes: 'No fasting required',
  },
  {
    id: 'SVC-0008',
    code: 'IMG-0001',
    name: 'Digital X-Ray',
    description: 'Digital radiography for chest, spine, limbs, or other body parts',
    category: 'imaging',
    department: 'radiology',
    serviceType: 'both',
    billingType: 'variable',
    basePrice: 600,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 15,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 1450,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Price varies by body part',
  },
  {
    id: 'SVC-0009',
    code: 'IMG-0002',
    name: 'Ultrasound Abdomen',
    description: 'Complete abdominal ultrasound scan covering liver, kidney, spleen, pancreas',
    category: 'imaging',
    department: 'radiology',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 1200,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 30,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 680,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-21'),
    notes: 'Requires 4-6 hours fasting',
  },
  {
    id: 'SVC-0010',
    code: 'IMG-0003',
    name: 'CT Scan - Plain',
    description: 'Computed tomography scan without contrast',
    category: 'imaging',
    department: 'radiology',
    serviceType: 'both',
    billingType: 'variable',
    basePrice: 5000,
    taxCategory: 'gst_18',
    hsnCode: '9993',
    duration: 30,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'partial',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 320,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-20'),
    notes: 'Price varies by body region',
  },
  {
    id: 'SVC-0011',
    code: 'IMG-0004',
    name: 'MRI Scan - Plain',
    description: 'Magnetic resonance imaging without contrast',
    category: 'imaging',
    department: 'radiology',
    serviceType: 'both',
    billingType: 'variable',
    basePrice: 8000,
    taxCategory: 'gst_18',
    hsnCode: '9993',
    duration: 45,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'partial',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 180,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-19'),
    notes: 'No metallic implants allowed',
  },
  {
    id: 'SVC-0012',
    code: 'CAR-0001',
    name: 'ECG (12 Lead)',
    description: '12-lead electrocardiogram with interpretation',
    category: 'cardiology',
    department: 'cardiology',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 400,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 15,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 1890,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: '',
  },
  {
    id: 'SVC-0013',
    code: 'CAR-0002',
    name: '2D Echocardiography',
    description: 'Two-dimensional echocardiogram with Doppler analysis',
    category: 'cardiology',
    department: 'cardiology',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 2500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 30,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 540,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-21'),
    notes: '',
  },
  {
    id: 'SVC-0014',
    code: 'CAR-0003',
    name: 'Treadmill Test (TMT)',
    description: 'Stress test with continuous ECG monitoring during exercise',
    category: 'cardiology',
    department: 'cardiology',
    serviceType: 'opd',
    billingType: 'fixed',
    basePrice: 1800,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 45,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 280,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-18'),
    notes: 'Comfortable clothing and shoes required',
  },
  {
    id: 'SVC-0015',
    code: 'THR-0001',
    name: 'Physiotherapy Session',
    description: 'Individual physiotherapy session with trained therapist',
    category: 'therapy',
    department: 'physiotherapy',
    serviceType: 'both',
    billingType: 'per_unit',
    basePrice: 600,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 45,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'partial',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 1120,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Package rates available',
  },
  {
    id: 'SVC-0016',
    code: 'DEN-0001',
    name: 'Dental Scaling & Polishing',
    description: 'Professional teeth cleaning and polishing',
    category: 'dental',
    department: 'dental',
    serviceType: 'opd',
    billingType: 'fixed',
    basePrice: 1500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 45,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'not_covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 380,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-20'),
    notes: '',
  },
  {
    id: 'SVC-0017',
    code: 'DEN-0002',
    name: 'Root Canal Treatment',
    description: 'Endodontic treatment for infected tooth pulp',
    category: 'dental',
    department: 'dental',
    serviceType: 'opd',
    billingType: 'variable',
    basePrice: 5000,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 90,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'partial',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 150,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-19'),
    notes: 'Price varies by tooth type (₹5,000 - ₹12,000)',
  },
  {
    id: 'SVC-0018',
    code: 'NEP-0001',
    name: 'Dialysis Session',
    description: 'Hemodialysis session (4 hours) including consumables',
    category: 'nephrology',
    department: 'nephrology',
    serviceType: 'both',
    billingType: 'per_unit',
    basePrice: 3500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 4,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 2400,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Regular dialysis package available',
  },
  {
    id: 'SVC-0019',
    code: 'INP-0001',
    name: 'General Ward - Per Day',
    description: 'General ward accommodation with nursing care',
    category: 'inpatient',
    department: 'general',
    serviceType: 'ipd',
    billingType: 'per_day',
    basePrice: 2000,
    taxCategory: 'gst_12',
    hsnCode: '9963',
    duration: 24,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 890,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Shared room (4 beds)',
  },
  {
    id: 'SVC-0020',
    code: 'INP-0002',
    name: 'Semi-Private Room - Per Day',
    description: 'Semi-private room with attached bathroom',
    category: 'inpatient',
    department: 'general',
    serviceType: 'ipd',
    billingType: 'per_day',
    basePrice: 4000,
    taxCategory: 'gst_12',
    hsnCode: '9963',
    duration: 24,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 560,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Shared room (2 beds)',
  },
  {
    id: 'SVC-0021',
    code: 'INP-0003',
    name: 'Private Deluxe Room - Per Day',
    description: 'Private deluxe room with AC, TV, and attendant bed',
    category: 'inpatient',
    department: 'general',
    serviceType: 'ipd',
    billingType: 'per_day',
    basePrice: 6500,
    taxCategory: 'gst_12',
    hsnCode: '9963',
    duration: 24,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'partial',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 340,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-21'),
    notes: 'Single occupancy',
  },
  {
    id: 'SVC-0022',
    code: 'INP-0004',
    name: 'ICU - Per Day',
    description: 'Intensive Care Unit with 24/7 monitoring and critical care',
    category: 'inpatient',
    department: 'icu',
    serviceType: 'ipd',
    billingType: 'per_day',
    basePrice: 12000,
    taxCategory: 'gst_12',
    hsnCode: '9963',
    duration: 24,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: true,
    usageCount: 210,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Includes basic monitoring and nursing',
  },
  {
    id: 'SVC-0023',
    code: 'EMR-0001',
    name: 'Emergency Registration',
    description: 'Emergency department registration and initial assessment',
    category: 'emergency',
    department: 'emergency',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 30,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: true,
    usageCount: 1560,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: '24/7 service',
  },
  {
    id: 'SVC-0024',
    code: 'SUR-0001',
    name: 'Minor Surgical Procedure',
    description: 'Minor surgical procedures like suturing, incision & drainage',
    category: 'surgical',
    department: 'general',
    serviceType: 'both',
    billingType: 'variable',
    basePrice: 2500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 30,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: false,
    isEmergency: false,
    usageCount: 420,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-21'),
    notes: 'Price varies by procedure complexity',
  },
  {
    id: 'SVC-0025',
    code: 'PRV-0001',
    name: 'Annual Health Checkup - Basic',
    description: 'Basic health screening package with blood tests, ECG, and consultation',
    category: 'preventive',
    department: 'general',
    serviceType: 'opd',
    billingType: 'package',
    basePrice: 2500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 3,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'varies',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 680,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-20'),
    notes: 'Includes CBC, Lipid, Sugar, Kidney, Liver function, Thyroid, ECG, Consultation',
    isPackage: true,
    packageServices: ['SVC-0004', 'SVC-0005', 'SVC-0006', 'SVC-0007', 'SVC-0012', 'SVC-0001'],
  },
  {
    id: 'SVC-0026',
    code: 'PRV-0002',
    name: 'Executive Health Checkup',
    description: 'Comprehensive health screening with advanced diagnostics',
    category: 'preventive',
    department: 'general',
    serviceType: 'opd',
    billingType: 'package',
    basePrice: 8500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 1,
    durationUnit: 'days',
    status: 'active',
    insuranceCategory: 'varies',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 240,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-19'),
    notes: 'Includes all basic tests + Echo, TMT, Ultrasound, Specialist consultations',
    isPackage: true,
    packageServices: ['SVC-0004', 'SVC-0005', 'SVC-0006', 'SVC-0007', 'SVC-0012', 'SVC-0013', 'SVC-0014', 'SVC-0009', 'SVC-0002'],
  },
  {
    id: 'SVC-0027',
    code: 'MAT-0001',
    name: 'Normal Delivery Package',
    description: 'Complete normal delivery package including pre & post natal care',
    category: 'maternity',
    department: 'gynecology',
    serviceType: 'ipd',
    billingType: 'package',
    basePrice: 45000,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 3,
    durationUnit: 'days',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 120,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-18'),
    notes: '3 days room, delivery charges, medications, newborn care',
    isPackage: true,
  },
  {
    id: 'SVC-0028',
    code: 'MAT-0002',
    name: 'C-Section Delivery Package',
    description: 'Complete cesarean delivery package with extended care',
    category: 'maternity',
    department: 'gynecology',
    serviceType: 'ipd',
    billingType: 'package',
    basePrice: 85000,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 5,
    durationUnit: 'days',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 90,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-17'),
    notes: '5 days room, surgery, medications, newborn care, post-op care',
    isPackage: true,
  },
  {
    id: 'SVC-0029',
    code: 'PED-0001',
    name: 'Pediatric Consultation',
    description: 'Consultation with pediatrician for children 0-18 years',
    category: 'pediatric',
    department: 'pediatrics',
    serviceType: 'both',
    billingType: 'fixed',
    basePrice: 600,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 20,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 780,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: '',
  },
  {
    id: 'SVC-0030',
    code: 'PED-0002',
    name: 'Vaccination - Standard',
    description: 'Standard childhood vaccination as per IAP schedule',
    category: 'pediatric',
    department: 'pediatrics',
    serviceType: 'opd',
    billingType: 'variable',
    basePrice: 500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 15,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'varies',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 1450,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Price varies by vaccine type',
  },
  {
    id: 'SVC-0031',
    code: 'OPH-0001',
    name: 'Eye Examination - Comprehensive',
    description: 'Complete eye examination including refraction, fundus, and slit lamp',
    category: 'consultation',
    department: 'ophthalmology',
    serviceType: 'opd',
    billingType: 'fixed',
    basePrice: 800,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 30,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 520,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-20'),
    notes: '',
  },
  {
    id: 'SVC-0032',
    code: 'ONT-0001',
    name: 'Chemotherapy - Standard Protocol',
    description: 'Standard chemotherapy session excluding drug costs',
    category: 'oncology',
    department: 'oncology',
    serviceType: 'both',
    billingType: 'per_unit',
    basePrice: 5000,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 4,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 180,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-19'),
    notes: 'Drug costs billed separately',
  },
  {
    id: 'SVC-0033',
    code: 'OLD-0001',
    name: 'Teleconsultation - General',
    description: 'Video consultation with general physician',
    category: 'consultation',
    department: 'general',
    serviceType: 'opd',
    billingType: 'fixed',
    basePrice: 300,
    taxCategory: 'gst_18',
    hsnCode: '9983',
    duration: 15,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'not_covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 680,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Available 9 AM - 9 PM',
  },
  {
    id: 'SVC-0034',
    code: 'DIS-0001',
    name: 'Home Sample Collection',
    description: 'Sample collection from patient home for lab tests',
    category: 'laboratory',
    department: 'pathology',
    serviceType: 'opd',
    billingType: 'fixed',
    basePrice: 200,
    taxCategory: 'gst_18',
    hsnCode: '9983',
    duration: 30,
    durationUnit: 'minutes',
    status: 'active',
    insuranceCategory: 'not_covered',
    requiresAppointment: true,
    isEmergency: false,
    usageCount: 450,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Available within 10km radius',
  },
  {
    id: 'SVC-0035',
    code: 'DIS-0002',
    name: 'Ambulance Service - Basic',
    description: 'Basic life support ambulance transport',
    category: 'emergency',
    department: 'emergency',
    serviceType: 'both',
    billingType: 'variable',
    basePrice: 1500,
    taxCategory: 'exempt',
    hsnCode: '9993',
    duration: 1,
    durationUnit: 'hours',
    status: 'active',
    insuranceCategory: 'partial',
    requiresAppointment: false,
    isEmergency: true,
    usageCount: 280,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-01-22'),
    notes: 'Base rate + ₹25/km',
  },
];

// Service Categories Summary
export const categoryStats = [
  { category: 'consultation', count: 8, revenue: 245000 },
  { category: 'laboratory', count: 6, revenue: 890000 },
  { category: 'imaging', count: 4, revenue: 520000 },
  { category: 'cardiology', count: 3, revenue: 380000 },
  { category: 'therapy', count: 1, revenue: 120000 },
  { category: 'dental', count: 2, revenue: 180000 },
  { category: 'inpatient', count: 4, revenue: 1200000 },
  { category: 'emergency', count: 3, revenue: 340000 },
  { category: 'surgical', count: 1, revenue: 450000 },
  { category: 'preventive', count: 2, revenue: 280000 },
  { category: 'maternity', count: 2, revenue: 560000 },
  { category: 'pediatric', count: 2, revenue: 195000 },
  { category: 'oncology', count: 1, revenue: 320000 },
];
