import { addDays, subDays, setHours, setMinutes } from 'date-fns';

const today = new Date();

export const mockAppointments = [
  {
    id: 'apt-1',
    patientName: 'Rahul Sharma',
    patientId: 'MRN-2024-0001',
    patientPhone: '+91 98765 43210',
    patientAge: 45,
    patientGender: 'Male',
    doctorId: 'dr1',
    doctorName: 'Dr. Priya Patel',
    department: 'general',
    appointmentType: 'consultation',
    date: today,
    time: '09:00 AM',
    status: 'confirmed',
    notes: 'First visit for persistent cough',
    createdAt: subDays(today, 2),
    tags: ['tag2', 'tag10'],
    categories: ['cat1'],
  },
  {
    id: 'apt-2',
    patientName: 'Sneha Gupta',
    patientId: 'MRN-2024-0002',
    patientPhone: '+91 98765 43211',
    patientAge: 32,
    patientGender: 'Female',
    doctorId: 'dr2',
    doctorName: 'Dr. Rajesh Kumar',
    department: 'cardiology',
    appointmentType: 'checkup',
    date: today,
    time: '10:00 AM',
    status: 'scheduled',
    notes: 'Annual cardiac checkup',
    createdAt: subDays(today, 5),
    tags: ['tag5'],
    categories: ['cat5'],
  },
  {
    id: 'apt-3',
    patientName: 'Amit Patel',
    patientId: 'MRN-2024-0003',
    patientPhone: '+91 98765 43212',
    patientAge: 28,
    patientGender: 'Male',
    doctorId: 'dr4',
    doctorName: 'Dr. Amit Sharma',
    department: 'orthopedics',
    appointmentType: 'follow-up',
    date: today,
    time: '11:30 AM',
    status: 'in-progress',
    notes: 'Follow-up after knee surgery',
    createdAt: subDays(today, 1),
    tags: ['tag1', 'tag2'],
    categories: ['cat2'],
  },
  {
    id: 'apt-4',
    patientName: 'Priya Verma',
    patientId: 'MRN-2024-0004',
    patientPhone: '+91 98765 43213',
    patientAge: 55,
    patientGender: 'Female',
    doctorId: 'dr3',
    doctorName: 'Dr. Sunita Rao',
    department: 'pediatrics',
    appointmentType: 'vaccination',
    date: today,
    time: '02:00 PM',
    status: 'scheduled',
    notes: 'Child vaccination - 6 months',
    createdAt: subDays(today, 3),
    tags: ['tag9'],
    categories: ['cat4'],
  },
  {
    id: 'apt-5',
    patientName: 'Vikram Mehta',
    patientId: 'MRN-2024-0005',
    patientPhone: '+91 98765 43214',
    patientAge: 62,
    patientGender: 'Male',
    doctorId: 'dr2',
    doctorName: 'Dr. Rajesh Kumar',
    department: 'cardiology',
    appointmentType: 'procedure',
    date: addDays(today, 1),
    time: '09:30 AM',
    status: 'confirmed',
    notes: 'ECG and stress test',
    createdAt: subDays(today, 7),
    tags: ['tag10'],
    categories: ['cat5'],
  },
  {
    id: 'apt-6',
    patientName: 'Anjali Reddy',
    patientId: 'MRN-2024-0006',
    patientPhone: '+91 98765 43215',
    patientAge: 38,
    patientGender: 'Female',
    doctorId: 'dr5',
    doctorName: 'Dr. Meera Nair',
    department: 'dermatology',
    appointmentType: 'consultation',
    date: addDays(today, 1),
    time: '11:00 AM',
    status: 'scheduled',
    notes: 'Skin allergy consultation',
    createdAt: subDays(today, 2),
    tags: ['tag6'],
    categories: ['cat1'],
  },
  {
    id: 'apt-7',
    patientName: 'Suresh Kumar',
    patientId: 'MRN-2024-0007',
    patientPhone: '+91 98765 43216',
    patientAge: 48,
    patientGender: 'Male',
    doctorId: 'dr6',
    doctorName: 'Dr. Vikram Singh',
    department: 'neurology',
    appointmentType: 'follow-up',
    date: subDays(today, 1),
    time: '03:00 PM',
    status: 'completed',
    notes: 'Post-treatment evaluation',
    createdAt: subDays(today, 10),
    tags: ['tag2'],
    categories: ['cat3'],
  },
  {
    id: 'apt-8',
    patientName: 'Meena Joshi',
    patientId: 'MRN-2024-0008',
    patientPhone: '+91 98765 43217',
    patientAge: 29,
    patientGender: 'Female',
    doctorId: 'dr1',
    doctorName: 'Dr. Priya Patel',
    department: 'general',
    appointmentType: 'lab-test',
    date: subDays(today, 1),
    time: '10:30 AM',
    status: 'no-show',
    notes: 'Blood test and urinalysis',
    createdAt: subDays(today, 4),
    tags: ['tag4'],
    categories: [],
  },
];
