// Mock drug interactions database
export const DRUG_INTERACTIONS_DB = [
  {
    drug1: 'Warfarin',
    drug2: 'Aspirin',
    severity: 'severe',
    description: 'Increased risk of bleeding when anticoagulants are combined with antiplatelet agents.',
    recommendation: 'Avoid combination unless specifically indicated. Monitor closely for signs of bleeding.',
  },
  {
    drug1: 'Warfarin',
    drug2: 'Ibuprofen',
    severity: 'severe',
    description: 'NSAIDs can increase anticoagulant effect and risk of GI bleeding.',
    recommendation: 'Use alternative pain relief (acetaminophen). If NSAID required, use lowest dose for shortest duration.',
  },
  {
    drug1: 'Metformin',
    drug2: 'Lisinopril',
    severity: 'minor',
    description: 'ACE inhibitors may enhance the hypoglycemic effect of metformin.',
    recommendation: 'Monitor blood glucose levels. This combination is commonly used and generally safe.',
  },
  {
    drug1: 'Sertraline',
    drug2: 'Tramadol',
    severity: 'severe',
    description: 'Risk of serotonin syndrome when SSRIs are combined with tramadol.',
    recommendation: 'Avoid combination. Use alternative pain medication or antidepressant.',
  },
  {
    drug1: 'Amlodipine',
    drug2: 'Atorvastatin',
    severity: 'moderate',
    description: 'Amlodipine may increase atorvastatin levels, increasing risk of myopathy.',
    recommendation: 'Limit atorvastatin dose to 20mg daily when used with amlodipine.',
  },
  {
    drug1: 'Lisinopril',
    drug2: 'Spironolactone',
    severity: 'moderate',
    description: 'Both drugs can increase potassium levels, risking hyperkalemia.',
    recommendation: 'Monitor potassium levels regularly. Avoid high-potassium foods.',
  },
  {
    drug1: 'Metoprolol',
    drug2: 'Amlodipine',
    severity: 'moderate',
    description: 'Additive effects on heart rate and blood pressure.',
    recommendation: 'Monitor heart rate and blood pressure. Start with lower doses.',
  },
  {
    drug1: 'Omeprazole',
    drug2: 'Clopidogrel',
    severity: 'moderate',
    description: 'Omeprazole may reduce the antiplatelet effect of clopidogrel.',
    recommendation: 'Consider using pantoprazole instead, which has less interaction.',
  },
  {
    drug1: 'Ciprofloxacin',
    drug2: 'Warfarin',
    severity: 'severe',
    description: 'Ciprofloxacin significantly increases warfarin effect and bleeding risk.',
    recommendation: 'If combination required, reduce warfarin dose and monitor INR frequently.',
  },
  {
    drug1: 'Gabapentin',
    drug2: 'Tramadol',
    severity: 'moderate',
    description: 'Both drugs can cause CNS depression; combined effect is additive.',
    recommendation: 'Use lower doses of each. Monitor for sedation and respiratory depression.',
  },
  {
    drug1: 'Azithromycin',
    drug2: 'Amiodarone',
    severity: 'severe',
    description: 'Both drugs prolong QT interval, increasing risk of dangerous arrhythmias.',
    recommendation: 'Avoid combination. Use alternative antibiotic.',
  },
  {
    drug1: 'Furosemide',
    drug2: 'Lisinopril',
    severity: 'minor',
    description: 'First dose hypotension may occur when starting ACE inhibitor with diuretic.',
    recommendation: 'Consider holding diuretic for 2-3 days before starting ACE inhibitor.',
  },
  {
    drug1: 'Levothyroxine',
    drug2: 'Omeprazole',
    severity: 'minor',
    description: 'PPIs may reduce levothyroxine absorption.',
    recommendation: 'Take levothyroxine at least 4 hours before PPI. Monitor TSH levels.',
  },
  {
    drug1: 'Sertraline',
    drug2: 'Aspirin',
    severity: 'moderate',
    description: 'SSRIs increase bleeding risk when combined with antiplatelet agents.',
    recommendation: 'Consider adding PPI for GI protection. Monitor for bleeding.',
  },
  {
    drug1: 'Metformin',
    drug2: 'Furosemide',
    severity: 'minor',
    description: 'Furosemide may slightly decrease metformin effectiveness.',
    recommendation: 'Monitor blood glucose. Adjust metformin dose if needed.',
  },
  {
    drug1: 'Duloxetine',
    drug2: 'Tramadol',
    severity: 'severe',
    description: 'Risk of serotonin syndrome when SNRIs are combined with tramadol.',
    recommendation: 'Avoid combination. Use alternative pain medication.',
  },
  {
    drug1: 'Hydrochlorothiazide',
    drug2: 'Lisinopril',
    severity: 'minor',
    description: 'Commonly prescribed combination. May cause excessive blood pressure lowering initially.',
    recommendation: 'Start with lower doses. This is a well-established therapeutic combination.',
  },
  {
    drug1: 'Prednisone',
    drug2: 'Ibuprofen',
    severity: 'moderate',
    description: 'Increased risk of GI ulceration and bleeding.',
    recommendation: 'Add PPI for gastroprotection. Use lowest effective doses.',
  },
  {
    drug1: 'Atorvastatin',
    drug2: 'Azithromycin',
    severity: 'minor',
    description: 'Azithromycin may slightly increase statin levels.',
    recommendation: 'Short-term antibiotic use is generally safe. Monitor for muscle pain.',
  },
  {
    drug1: 'Losartan',
    drug2: 'Spironolactone',
    severity: 'moderate',
    description: 'Both drugs can increase potassium levels.',
    recommendation: 'Monitor potassium levels regularly. Dietary potassium restriction may be needed.',
  },
];

// Patient allergy alerts
export const ALLERGY_DRUG_ALERTS = [
  {
    allergy: 'Penicillin',
    contraindicated: ['Amoxicillin', 'Ampicillin', 'Penicillin V'],
    crossReactivity: ['Cephalexin', 'Cefazolin'], // ~10% cross-reactivity
    recommendation: 'Avoid penicillin-class antibiotics. Use caution with cephalosporins.',
  },
  {
    allergy: 'Sulfa',
    contraindicated: ['Sulfamethoxazole', 'Sulfasalazine'],
    crossReactivity: ['Hydrochlorothiazide', 'Furosemide'],
    recommendation: 'Avoid sulfonamide antibiotics. Thiazide diuretics may be used with caution.',
  },
  {
    allergy: 'NSAIDs',
    contraindicated: ['Ibuprofen', 'Naproxen', 'Aspirin', 'Meloxicam'],
    crossReactivity: [],
    recommendation: 'Use acetaminophen for pain relief. Avoid all NSAIDs.',
  },
  {
    allergy: 'Codeine',
    contraindicated: ['Codeine', 'Hydrocodone', 'Oxycodone'],
    crossReactivity: ['Tramadol', 'Morphine'],
    recommendation: 'Avoid opioid analgesics. Use non-opioid alternatives.',
  },
];
