import { subHours, subDays } from 'date-fns';

const now = new Date();

// Mock refill requests
export const MOCK_REFILL_REQUESTS = [
  {
    id: 'ref-001',
    prescriptionId: 'rx-002',
    patientId: 'p-002',
    patientName: 'James Miller',
    patientMrn: 'MRN-2024-002',
    medicineName: 'Metformin',
    dosage: '1000mg',
    requestedAt: subHours(now, 3),
    status: 'pending',
    refillsRemaining: 5,
    lastFilledDate: subDays(now, 28),
    requestedBy: 'patient',
  },
  {
    id: 'ref-002',
    prescriptionId: 'rx-003',
    patientId: 'p-003',
    patientName: 'Sofia Garcia',
    patientMrn: 'MRN-2024-003',
    medicineName: 'Amlodipine',
    dosage: '5mg',
    requestedAt: subHours(now, 8),
    status: 'pending',
    refillsRemaining: 3,
    lastFilledDate: subDays(now, 25),
    requestedBy: 'pharmacy',
  },
  {
    id: 'ref-003',
    prescriptionId: 'rx-005',
    patientId: 'p-005',
    patientName: 'Maria Santos',
    patientMrn: 'MRN-2024-005',
    medicineName: 'Sumatriptan',
    dosage: '50mg',
    requestedAt: subDays(now, 1),
    status: 'approved',
    refillsRemaining: 4,
    lastFilledDate: subDays(now, 30),
    requestedBy: 'patient',
    processedAt: subHours(now, 20),
    processedBy: 'Dr. Michael Chen',
  },
  {
    id: 'ref-004',
    prescriptionId: 'rx-008',
    patientId: 'p-002',
    patientName: 'James Miller',
    patientMrn: 'MRN-2024-002',
    medicineName: 'Atorvastatin',
    dosage: '20mg',
    requestedAt: subDays(now, 2),
    status: 'denied',
    refillsRemaining: 2,
    lastFilledDate: subDays(now, 45),
    requestedBy: 'patient',
    processedAt: subDays(now, 1),
    processedBy: 'Dr. Emily Brown',
    denyReason: 'Lab work required before refill. Please schedule lipid panel.',
  },
  {
    id: 'ref-005',
    prescriptionId: 'rx-001',
    patientId: 'p-001',
    patientName: 'Emma Wilson',
    patientMrn: 'MRN-2024-001',
    medicineName: 'Azithromycin',
    dosage: '500mg',
    requestedAt: subHours(now, 1),
    status: 'pending',
    refillsRemaining: 2,
    lastFilledDate: subDays(now, 5),
    requestedBy: 'patient',
  },
];
