export const categories = [
  {
    id: "1",
    name: "Crystal Bracelets",
    description: "Handcrafted with amethyst, rose quartz & healing stones",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&h=600&fit=crop",
    startingPrice: 499,
    slug: "crystal-bracelets",
  },
  {
    id: "2",
    name: "Healing Spheres",
    description: "Clear quartz & crystal spheres for meditation",
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&h=600&fit=crop",
    startingPrice: 1299,
    slug: "healing-spheres",
  },
  {
    id: "3",
    name: "Spiritual Pyramids",
    description: "Orgonite pyramids charged with positive energy",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=600&fit=crop",
    startingPrice: 899,
    slug: "spiritual-pyramids",
  },
  {
    id: "4",
    name: "Energy Stones",
    description: "Tumbled & polished stones for chakra healing",
    image: "https://images.unsplash.com/photo-1600298882525-c4b2100e1000?w=600&h=600&fit=crop",
    startingPrice: 199,
    slug: "energy-stones",
  },
  {
    id: "5",
    name: "Mala Prayer Beads",
    description: "Rudraksha & crystal mala for japa meditation",
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&h=600&fit=crop",
    startingPrice: 699,
    slug: "mala-prayer-beads",
  },
  {
    id: "6",
    name: "Crystal Pendulums",
    description: "Amethyst & quartz pendulums for divination",
    image: "https://images.unsplash.com/photo-1603344797033-f0f4f587ab60?w=600&h=600&fit=crop",
    startingPrice: 349,
    slug: "crystal-pendulums",
  },
  {
    id: "7",
    name: "Amethyst Geodes",
    description: "Natural geode bookends & display pieces",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&h=600&fit=crop",
    startingPrice: 2499,
    slug: "amethyst-geodes",
  },
  {
    id: "8",
    name: "Chakra Stone Sets",
    description: "7 chakra healing stones for energy alignment",
    image: "https://images.unsplash.com/photo-1600298882525-c4b2100e1000?w=600&h=600&fit=crop",
    startingPrice: 599,
    slug: "chakra-stone-sets",
  },
];

export const products = [
  {
    id: "p1",
    name: "Amethyst Crystal Bracelet",
    description: "Beautiful handcrafted amethyst bracelet for spiritual protection and inner peace. Each bead is carefully selected for its deep purple hue and natural energy.",
    price: 699,
    originalPrice: 999,
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["bracelet", "amethyst", "healing"],
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "p2",
    name: "Rose Quartz Healing Sphere",
    description: "Polished rose quartz sphere perfect for meditation and heart chakra healing. Promotes love, compassion, and emotional balance.",
    price: 1499,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["sphere", "rose quartz", "meditation"],
    inStock: true,
    rating: 4.9,
    reviews: 89,
  },
  {
    id: "p3",
    name: "Orgonite Energy Pyramid",
    description: "Handmade orgonite pyramid with copper coils and mixed crystals. Transmutes negative energy into positive vibrations.",
    price: 1299,
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=600&fit=crop",
    category: "Meditation",
    tags: ["pyramid", "orgonite", "energy"],
    inStock: true,
    rating: 4.7,
    reviews: 56,
  },
  {
    id: "p4",
    name: "Tiger Eye Tumbled Stones",
    description: "Set of 5 polished tiger eye stones for courage, confidence, and willpower. Perfect for carrying in your pocket.",
    price: 299,
    image: "https://images.unsplash.com/photo-1600298882525-c4b2100e1000?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["tumbled", "tiger eye", "chakra"],
    inStock: true,
    rating: 4.6,
    reviews: 203,
  },
  {
    id: "p5",
    name: "108 Bead Rudraksha Mala",
    description: "Traditional 108 bead rudraksha mala for japa meditation and spiritual practice. Blessed and energized.",
    price: 899,
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&h=600&fit=crop",
    category: "Jewelry",
    tags: ["mala", "rudraksha", "meditation"],
    inStock: true,
    rating: 4.9,
    reviews: 167,
  },
  {
    id: "p6",
    name: "Clear Quartz Pendulum",
    description: "Natural clear quartz pendulum for dowsing, divination, and energy healing. Comes with a velvet pouch.",
    price: 449,
    image: "https://images.unsplash.com/photo-1603344797033-f0f4f587ab60?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["pendulum", "quartz", "divination"],
    inStock: true,
    rating: 4.5,
    reviews: 78,
  },
  {
    id: "p7",
    name: "Amethyst Geode Bookend",
    description: "Stunning natural amethyst geode bookend. Each piece is unique with deep purple crystals. Weighs approximately 2kg.",
    price: 3499,
    originalPrice: 4499,
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["geode", "amethyst", "decor"],
    inStock: true,
    rating: 4.8,
    reviews: 34,
  },
  {
    id: "p8",
    name: "7 Chakra Stone Set",
    description: "Complete set of 7 chakra healing stones with a cotton pouch and chakra guide card. Balance all your energy centers.",
    price: 799,
    image: "https://images.unsplash.com/photo-1600298882525-c4b2100e1000?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["chakra", "set", "healing"],
    inStock: true,
    rating: 4.7,
    reviews: 145,
  },
  {
    id: "p9",
    name: "Black Tourmaline Tower",
    description: "Natural black tourmaline crystal tower for protection against negative energies and EMF radiation.",
    price: 599,
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&h=600&fit=crop",
    category: "Vastu",
    tags: ["tower", "tourmaline", "protection"],
    inStock: true,
    rating: 4.6,
    reviews: 92,
  },
  {
    id: "p10",
    name: "Citrine Abundance Bracelet",
    description: "Natural citrine crystal bracelet for attracting abundance, prosperity, and positive energy. Known as the merchant's stone.",
    price: 799,
    originalPrice: 1099,
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&h=600&fit=crop",
    category: "Jewelry",
    tags: ["bracelet", "citrine", "abundance"],
    inStock: true,
    rating: 4.8,
    reviews: 110,
  },
  {
    id: "p11",
    name: "Selenite Charging Plate",
    description: "Polished selenite plate for cleansing and charging your crystals. Essential tool for crystal care.",
    price: 699,
    image: "https://images.unsplash.com/photo-1603344797033-f0f4f587ab60?w=600&h=600&fit=crop",
    category: "Meditation",
    tags: ["selenite", "charging", "cleansing"],
    inStock: true,
    rating: 4.7,
    reviews: 65,
  },
  {
    id: "p12",
    name: "Vastu Crystal Tree",
    description: "Handcrafted crystal gem tree with mixed stones for Vastu correction. Attracts positive energy to your space.",
    price: 1599,
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&h=600&fit=crop",
    category: "Vastu",
    tags: ["tree", "vastu", "decor"],
    inStock: true,
    rating: 4.9,
    reviews: 87,
  },
  {
    id: "p13",
    name: "Pyrite Money Magnet Bracelet",
    description: "Genuine pyrite bracelet known as the 'stone of wealth'. Activates the solar plexus chakra to attract money, opportunity and prosperity.",
    price: 999,
    originalPrice: 1499,
    image: "https://images.unsplash.com/photo-1610375461246-83df859d849d?w=600&h=600&fit=crop",
    category: "Jewelry",
    tags: ["bracelet", "pyrite", "wealth"],
    inStock: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: "p14",
    name: "Seven Chakra Crystal Tree",
    description: "Handcrafted gemstone tree with 7 chakra stones on a natural quartz base. Perfect Vastu remedy for home and office harmony.",
    price: 1899,
    originalPrice: 2499,
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&h=600&fit=crop",
    category: "Vastu",
    tags: ["tree", "chakra", "vastu", "decor"],
    inStock: true,
    rating: 4.9,
    reviews: 112,
  },
  {
    id: "p15",
    name: "Rose Quartz Sphere Ball",
    description: "Polished rose quartz sphere on wooden stand. Radiates loving energy in all directions — ideal for the bedroom or living space.",
    price: 1799,
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["sphere", "rose quartz", "decor"],
    inStock: true,
    rating: 4.8,
    reviews: 73,
  },
  {
    id: "p16",
    name: "Amethyst Cluster Geode",
    description: "Raw amethyst cluster from Brazil. Natural formation that purifies the surrounding aura and amplifies meditation.",
    price: 2299,
    originalPrice: 2999,
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["cluster", "amethyst", "geode"],
    inStock: true,
    rating: 4.9,
    reviews: 64,
  },
  {
    id: "p17",
    name: "Clear Quartz Pyramid",
    description: "Hand-cut clear quartz pyramid for energy amplification, Vastu correction and EMF protection. Perfect for the meditation altar.",
    price: 1199,
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=600&fit=crop",
    category: "Vastu",
    tags: ["pyramid", "quartz", "vastu"],
    inStock: true,
    rating: 4.7,
    reviews: 98,
  },
  {
    id: "p18",
    name: "Moonstone Adjustable Ring",
    description: "Sterling silver ring set with rainbow moonstone. Enhances feminine energy, intuition and emotional balance.",
    price: 849,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1603344797033-f0f4f587ab60?w=600&h=600&fit=crop",
    category: "Jewelry",
    tags: ["ring", "moonstone", "silver"],
    inStock: true,
    rating: 4.7,
    reviews: 81,
  },
  {
    id: "p19",
    name: "Lapis Lazuli Pendant",
    description: "Deep blue lapis lazuli pendant with silver bail. Stone of wisdom and truth — opens the third eye and throat chakras.",
    price: 749,
    image: "https://images.unsplash.com/photo-1611425143202-fd3f1f4b9a09?w=600&h=600&fit=crop",
    category: "Jewelry",
    tags: ["pendant", "lapis lazuli", "wisdom"],
    inStock: true,
    rating: 4.8,
    reviews: 59,
  },
  {
    id: "p20",
    name: "Green Aventurine Money Tree",
    description: "Lucky money tree with green aventurine leaves on a pyrite base. Brings abundance, growth and good fortune to your space.",
    price: 2199,
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&h=600&fit=crop",
    category: "Vastu",
    tags: ["tree", "aventurine", "abundance"],
    inStock: true,
    rating: 4.9,
    reviews: 134,
  },
  {
    id: "p21",
    name: "Carnelian Tumbled Stones (Pack of 5)",
    description: "Vibrant orange carnelian tumbles. Boosts confidence, creativity and motivation. Carry one in your pocket daily.",
    price: 349,
    image: "https://images.unsplash.com/photo-1600298882525-c4b2100e1000?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["tumbled", "carnelian", "creativity"],
    inStock: true,
    rating: 4.6,
    reviews: 102,
  },
  {
    id: "p22",
    name: "Labradorite Sphere on Stand",
    description: "Mystical labradorite sphere flashing blue and gold fire. Enhances intuition, psychic ability and spiritual awakening.",
    price: 2499,
    originalPrice: 3199,
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&h=600&fit=crop",
    category: "Crystals",
    tags: ["sphere", "labradorite", "intuition"],
    inStock: true,
    rating: 4.9,
    reviews: 47,
  },
];

export const testimonials = [
  {
    id: 1,
    text: "The amethyst bracelet has brought such calm to my life. You can truly feel the energy in these crystals.",
    name: "Priya Sharma",
    location: "Mumbai",
    initial: "P",
  },
  {
    id: 2,
    text: "Ordered a quartz pyramid for my home office. The quality is outstanding and delivery was swift.",
    name: "Rahul Verma",
    location: "Delhi",
    initial: "R",
  },
  {
    id: 3,
    text: "Their Vastu consultation helped me place my crystals perfectly. My home feels so much more peaceful now.",
    name: "Ananya Patel",
    location: "Ahmedabad",
    initial: "A",
  },
];

export const blogPosts = [
  {
    id: "b1",
    slug: "healing-power-of-amethyst",
    title: "The Healing Power of Amethyst",
    excerpt: "Discover why amethyst has been revered for centuries as a stone of spiritual protection,...",
    category: "CRYSTAL AURA",
    date: "March 15, 2026",
    readTime: "5 MIN READ",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&h=400&fit=crop",
    author: "Aanya Mehta",
    content: [
      "Amethyst is the violet flame of the mineral kingdom — a stone whose deep purple light has guided seekers for over two thousand years. From ancient Greek goddesses to Tibetan monks, civilizations across time have turned to amethyst to quiet the mind and lift the spirit.",
      "## Spiritual significance",
      "Worn historically as a talisman against intoxication of all kinds — wine, ego, lower vibrations — amethyst is the gentle guardian of the crown chakra. It opens the third eye, sharpens intuition, and creates a luminous shield around the aura that filters out heaviness.",
      "## How to use it",
      "Place a tumbled amethyst beneath your pillow to deepen sleep and invite prophetic dreams. Hold a polished sphere during meditation to dissolve mental chatter. Wear an amethyst bracelet daily to remain centered through chaotic environments.",
      "## Care",
      "Cleanse weekly with sage smoke or moonlight — never direct sunlight, which fades its colour. Charge on a selenite plate to keep the stone vibrant and clear.",
      "Amethyst doesn't shout — it whispers. Sit with it in stillness and you will hear it speak.",
    ],
  },
  {
    id: "b2",
    slug: "5-vastu-tips-harmonious-home",
    title: "5 Vastu Tips for a Harmonious Home",
    excerpt: "Learn how to place crystals and pyramids in your home to attract positive energy and...",
    category: "VASTU",
    date: "March 8, 2026",
    readTime: "7 MIN READ",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=400&fit=crop",
    author: "Vikram Joshi",
    content: [
      "Vastu Shastra is the ancient Indian science of spatial harmony — a way of arranging your home so that energy flows freely, prosperity gathers, and inhabitants thrive. Crystals are powerful Vastu remedies because they hold and amplify the elemental energies of earth.",
      "## 1. North-east — clarity",
      "Place a clear quartz pyramid or cluster in the north-east corner. This is the zone of consciousness, study and spiritual practice. Quartz amplifies clarity here.",
      "## 2. South-east — wealth",
      "Citrine and pyrite belong in the south-east — the fire corner ruled by Lakshmi. A small citrine geode on a south-east shelf magnetises abundance.",
      "## 3. South-west — stability",
      "Anchor the south-west with heavier stones like black tourmaline or red jasper. This grounds the family and protects relationships.",
      "## 4. Centre — equilibrium",
      "The brahmasthan (centre) of the home should remain open. A small selenite tower here radiates cleansing light through the entire space.",
      "## 5. Entrance — protection",
      "A black tourmaline cluster near the front door absorbs negativity entering the home. Pair with a clear quartz to invite positive frequencies.",
      "Begin with one corner. Notice how the room feels after a week. Vastu reveals itself gradually.",
    ],
  },
  {
    id: "b3",
    slug: "beginners-guide-chakra-healing",
    title: "Beginner's Guide to Chakra Healing",
    excerpt: "Understanding the seven chakras and how to use specific crystals to balance and align your...",
    category: "MEDITATION",
    date: "February 28, 2026",
    readTime: "8 MIN READ",
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&h=400&fit=crop",
    author: "Sage Iyer",
    content: [
      "Chakras are spinning wheels of energy aligned along the spine, from the base to the crown. When all seven flow in balance, you feel grounded, joyful, expressive and connected. When one is blocked, the imbalance ripples through body and mind.",
      "## The seven centres",
      "Each chakra resonates with a specific colour, element and crystal frequency. Working with the matching stone gently restores the chakra's natural rhythm.",
      "## A simple practice",
      "Lie down. Place a stone on each chakra point — red jasper at the root, carnelian at the sacral, citrine at the solar plexus, rose quartz on the heart, lapis at the throat, amethyst on the third eye, and clear quartz above the crown. Breathe slowly for ten minutes.",
      "## Daily integration",
      "You don't need a full lay-down ritual every day. Carry the stone of the chakra you most need to support. Confidence shaky? Pocket some citrine. Heart heavy? Wear rose quartz close to your skin.",
      "Healing is not a destination. It's a daily, gentle return to balance.",
    ],
  },
  {
    id: "b4",
    slug: "crystal-care-cleansing-charging",
    title: "Crystal Care: Cleansing & Charging",
    excerpt: "Learn the essential practices for keeping your crystals energetically pure and powerful...",
    category: "CRYSTAL AURA",
    date: "February 20, 2026",
    readTime: "6 MIN READ",
    image: "https://images.unsplash.com/photo-1600298882525-c4b2100e1000?w=600&h=400&fit=crop",
    author: "Aanya Mehta",
    content: [
      "Crystals absorb the energies they encounter. Over time they become saturated — much like a sponge full of water — and stop transmitting their gifts as clearly. Regular cleansing returns them to their original purity.",
      "## Why cleanse",
      "After heavy use, travel, or exposure to dense emotions, your stones feel dull to the touch. Cleansing resets them so they can hold and transmit energy at full intensity again.",
      "## Methods",
      "Sage smoke, palo santo, full moonlight, sound from a singing bowl, and selenite contact are the gentlest universal methods. Salt water and direct sunlight work for some stones but damage others — research before using.",
      "## Charging",
      "Once cleansed, set an intention as you hold the stone. This is charging. Place it on a windowsill under the full moon overnight, or on a selenite plate, to amplify the intention.",
      "Treat your crystals as living companions, not decorations. They reward devotion.",
    ],
  },
  {
    id: "b5",
    slug: "how-to-cleanse-charge-crystals",
    title: "How to Cleanse & Charge Your Crystals",
    excerpt: "A comprehensive guide to the most effective methods for purifying your healing stones...",
    category: "GUIDES",
    date: "February 15, 2026",
    readTime: "6 MIN READ",
    image: "https://images.unsplash.com/photo-1603344797033-f0f4f587ab60?w=600&h=400&fit=crop",
    author: "Sage Iyer",
    content: [
      "Every crystal in your collection deserves a regular ritual of renewal. Here is the comprehensive guide we share with first-time crystal keepers.",
      "## The four elements",
      "Each element offers a cleansing pathway. Earth: bury the stone in soil overnight. Water: rinse under cool running water (only for hard stones). Fire: pass through candle flame briefly. Air: smudge with sage or palo santo.",
      "## Sound cleansing",
      "Tibetan singing bowls, tuning forks at 432Hz, and even your own voice chanting OM will shake stagnant energy loose. Hold the stone near the source for one minute.",
      "## Moon water",
      "Leave a bowl of filtered water out under the full moon. The next morning, dip your stones in it briefly. This is the most loving cleansing for delicate crystals.",
      "## Frequency",
      "Cleanse new stones immediately. Cleanse working stones (jewelry, daily-carry tumbles) weekly. Cleanse altar stones with each new moon.",
      "Consistency matters more than method. Pick what you'll actually do.",
    ],
  },
  {
    id: "b6",
    slug: "meditation-with-crystal-spheres",
    title: "Meditation with Crystal Spheres",
    excerpt: "Unlock deeper states of consciousness using crystal spheres in your meditation practice...",
    category: "MEDITATION",
    date: "February 10, 2026",
    readTime: "5 MIN READ",
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&h=400&fit=crop",
    author: "Vikram Joshi",
    content: [
      "The sphere is the most balanced of all crystal forms — radiating energy uniformly in every direction. In meditation, this perfect symmetry helps the mind settle into a similar state of equilibrium.",
      "## Choosing your sphere",
      "Clear quartz amplifies any intention. Rose quartz softens the heart. Amethyst deepens insight. Labradorite opens psychic gates. Begin with whichever stone calls you most strongly.",
      "## The practice",
      "Sit comfortably. Cup the sphere in both palms at heart level. Soften your gaze on its surface. Notice the inclusions, the way light moves through it. Let your breath slow. Let thought dissolve.",
      "## What to expect",
      "After ten minutes, the sphere often feels warm and pulsing. This is your own energy in dialogue with the stone. Some people receive images, words, or quiet certainty. Others simply rest.",
      "Meditation with a sphere is not about effort. It is about allowing.",
    ],
  },
];

export const faqItems = [
  {
    question: "Are your crystals authentic and natural?",
    answer: "Yes! Every crystal in our collection is 100% natural and authentic. We source our crystals from trusted mines and suppliers across India, Brazil, Madagascar, and other renowned locations. Each stone comes with a certificate of authenticity.",
  },
  {
    question: "How do I choose the right crystal for me?",
    answer: "We recommend choosing crystals based on your intentions and what you're looking to attract or heal. You can browse by chakra, intention, or simply let your intuition guide you. Our team also offers free consultations to help you find the perfect stone.",
  },
  {
    question: "Do you offer Vastu consultation?",
    answer: "Yes! We provide complimentary Vastu guidance with every purchase. Our experts can advise you on the ideal placement of crystals in your home or office for maximum positive energy flow.",
  },
  {
    question: "What is your shipping policy?",
    answer: "We offer free shipping on all orders above ₹999 across India. Orders are carefully packed in protective materials to ensure your crystals arrive safely. Standard delivery takes 5-7 business days.",
  },
  {
    question: "How do I cleanse and charge my crystals?",
    answer: "We recommend cleansing your crystals with sage smoke, moonlight, or running water. To charge them, place them under the full moon or in sunlight (avoid prolonged sun for amethyst and rose quartz). Each order includes a crystal care guide.",
  },
  {
    question: "Do you accept returns?",
    answer: "We accept returns within 7 days of delivery if the product is unused and in its original packaging. Please contact us with photos of the product for a hassle-free return process.",
  },
  {
    question: "Can I request custom crystal jewelry?",
    answer: "Absolutely! We create custom bracelets, malas, and other jewelry pieces. Share your requirements and preferred crystals with us, and our artisans will craft a unique piece just for you.",
  },
  {
    question: "How are your crystals energetically cleansed before shipping?",
    answer: "Every crystal is purified through a ritual process that includes sage smudging, sound cleansing with singing bowls, and moonlight charging. This ensures your crystal arrives with pure, positive energy.",
  },
];

export const crystalTypes = [
  {
    name: "Amethyst",
    description: "Stone of spiritual protection and purification. Calms the mind and enhances intuition.",
    chakra: "Crown & Third Eye",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400&h=400&fit=crop",
  },
  {
    name: "Rose Quartz",
    description: "The stone of unconditional love. Opens the heart chakra and promotes self-love.",
    chakra: "Heart",
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=400&h=400&fit=crop",
  },
  {
    name: "Clear Quartz",
    description: "The master healer. Amplifies energy and intention. Programmable for any purpose.",
    chakra: "Crown",
    image: "https://images.unsplash.com/photo-1603344797033-f0f4f587ab60?w=400&h=400&fit=crop",
  },
  {
    name: "Black Tourmaline",
    description: "Powerful protection stone. Shields against negative energy and EMF radiation.",
    chakra: "Root",
    image: "https://images.unsplash.com/photo-1600298882525-c4b2100e1000?w=400&h=400&fit=crop",
  },
  {
    name: "Citrine",
    description: "The merchant's stone. Attracts abundance, prosperity, and positive energy.",
    chakra: "Solar Plexus",
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=400&h=400&fit=crop",
  },
  {
    name: "Tiger Eye",
    description: "Stone of courage and willpower. Enhances focus, determination, and confidence.",
    chakra: "Solar Plexus & Sacral",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=400&fit=crop",
  },
  {
    name: "Selenite",
    description: "Crystal of clarity and cleansing. Charges other crystals and clears energy blockages.",
    chakra: "Crown",
    image: "https://images.unsplash.com/photo-1603344797033-f0f4f587ab60?w=400&h=400&fit=crop",
  },
  {
    name: "Labradorite",
    description: "Stone of transformation. Enhances psychic abilities and protects the aura.",
    chakra: "Third Eye & Throat",
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=400&h=400&fit=crop",
  },
];

export const sunshineCrystals = [
  {
    name: "Citrine",
    description: "The literal 'sunshine stone'. Radiates warm solar energy, lifts mood, dispels gloom, and attracts joyful abundance.",
    chakra: "Solar Plexus",
    benefit: "Joy & Abundance",
    image: "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&h=600&fit=crop",
  },
  {
    name: "Sunstone",
    description: "Captures the vitality of the sun itself. Boosts confidence, energy and personal power on dull, low-light days.",
    chakra: "Sacral & Solar Plexus",
    benefit: "Vitality & Confidence",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&h=600&fit=crop",
  },
  {
    name: "Tiger Eye",
    description: "Golden bands of sunlit earth energy. Grounds you while sparking courage, focus and warm motivation.",
    chakra: "Solar Plexus",
    benefit: "Courage & Focus",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=600&fit=crop",
  },
  {
    name: "Yellow Jasper",
    description: "Nurturing solar stone. Brings steady, sunshine-like warmth, optimism and emotional resilience.",
    chakra: "Solar Plexus",
    benefit: "Optimism & Endurance",
    image: "https://images.unsplash.com/photo-1602491453631-e2a5ad90a131?w=600&h=600&fit=crop",
  },
  {
    name: "Amber",
    description: "Fossilized sunlight. Carries ancient warm energy that soothes, cleanses and uplifts the spirit.",
    chakra: "Solar Plexus & Sacral",
    benefit: "Warmth & Healing",
    image: "https://images.unsplash.com/photo-1611425143202-fd3f1f4b9a09?w=600&h=600&fit=crop",
  },
  {
    name: "Pyrite",
    description: "Known as 'fool's gold' — reflects bright, sun-like sparkle. Builds confidence, willpower and prosperity.",
    chakra: "Solar Plexus",
    benefit: "Willpower & Prosperity",
    image: "https://images.unsplash.com/photo-1610375461246-83df859d849d?w=600&h=600&fit=crop",
  },
];
