
import { addDays, setHours, setMinutes } from 'date-fns';

export const doctors = [
    { id: '1', name: 'Dr. Amit Sharma', specialty: 'Cardiology' },
    { id: '2', name: 'Dr. Priya Patel', specialty: 'Neurology' },
    { id: '3', name: 'Dr. Rahul Desai', specialty: 'Pediatrics' },
    { id: '4', name: 'Dr. Sneha Gupta', specialty: 'Orthopedics' },
    { id: '5', name: 'Dr. Vikram Singh', specialty: 'Dermatology' },
];

const today = new Date();

export const mockAppointments = [
    {
        id: '1',
        patient: { id: 'p1', name: 'Amit Vishwakarma', age: 45, phone: '555-0101', email: 'amit.vishwakarma@email.com' },
        doctor: doctors[0],
        date: today,
        startTime: '09:00',
        endTime: '09:30',
        type: 'Follow-up',
        status: 'confirmed',
        notes: 'Blood pressure check',
    },
    {
        id: '2',
        patient: { id: 'p2', name: 'Priya Sharma', age: 32, phone: '555-0102', email: 'priya.sharma@email.com' },
        doctor: doctors[0],
        date: today,
        startTime: '10:00',
        endTime: '10:45',
        type: 'Consultation',
        status: 'pending',
    },
    {
        id: '3',
        patient: { id: 'p3', name: 'Rahul Patel', age: 58, phone: '555-0103', email: 'rahul.patel@email.com' },
        doctor: doctors[0],
        date: today,
        startTime: '11:30',
        endTime: '12:00',
        type: 'Check-up',
        status: 'confirmed',
        notes: 'Annual physical exam',
    },
    {
        id: '4',
        patient: { id: 'p4', name: 'Sneha Desai', age: 28, phone: '555-0104', email: 'sneha.desai@email.com' },
        doctor: doctors[0],
        date: today,
        startTime: '14:00',
        endTime: '14:30',
        type: 'New Patient',
        status: 'confirmed',
    },
    {
        id: '5',
        patient: { id: 'p5', name: 'Vikram Gupta', age: 67, phone: '555-0105', email: 'vikram.gupta@email.com' },
        doctor: doctors[0],
        date: addDays(today, 1),
        startTime: '09:30',
        endTime: '10:00',
        type: 'Follow-up',
        status: 'pending',
        notes: 'Post-surgery review',
    },
    {
        id: '6',
        patient: { id: 'p6', name: 'Neha Singh', age: 41, phone: '555-0106', email: 'neha.singh@email.com' },
        doctor: doctors[0],
        date: addDays(today, 1),
        startTime: '11:00',
        endTime: '11:30',
        type: 'Consultation',
        status: 'delegated',
        delegatedFrom: doctors[1],
    },
    {
        id: '7',
        patient: { id: 'p7', name: 'Rohit Kumar', age: 52, phone: '555-0107', email: 'rohit.kumar@email.com' },
        doctor: doctors[0],
        date: addDays(today, 2),
        startTime: '10:00',
        endTime: '10:30',
        type: 'Check-up',
        status: 'confirmed',
    },
    {
        id: '8',
        patient: { id: 'p8', name: 'Anita Joshi', age: 35, phone: '555-0108', email: 'anita.joshi@email.com' },
        doctor: doctors[0],
        date: addDays(today, 3),
        startTime: '15:00',
        endTime: '15:45',
        type: 'New Patient',
        status: 'pending',
    },
    {
        id: '9',
        patient: { id: 'p9', name: 'Suresh Yadav', age: 73, phone: '555-0109', email: 'suresh.yadav@email.com' },
        doctor: doctors[0],
        date: addDays(today, 5),
        startTime: '09:00',
        endTime: '09:30',
        type: 'Follow-up',
        status: 'confirmed',
    },
    {
        id: '10',
        patient: { id: 'p10', name: 'Pooja Verma', age: 48, phone: '555-0110', email: 'pooja.verma@email.com' },
        doctor: doctors[0],
        date: addDays(today, -1),
        startTime: '14:30',
        endTime: '15:00',
        type: 'Consultation',
        status: 'cancelled',
    },
];
