// Mock data with Indian names

export const mockPatients = [
  {
    id: '1',
    full_name: 'Rajesh Kumar Sharma',
    age: 45,
    gender: 'Male',
    phone: '+91 98765 43210',
    email: 'rajesh.sharma@email.com',
    blood_group: 'B+',
    address: '123, Sector 15, Noida, UP',
    emergency_contact: '+91 98765 43211',
    medical_history: 'Diabetes Type 2',
    created_at: '2025-01-01',
  },
  {
    id: '2',
    full_name: 'Priya Patel',
    age: 32,
    gender: 'Female',
    phone: '+91 87654 32109',
    email: 'priya.patel@email.com',
    blood_group: 'O+',
    address: '456, MG Road, Ahmedabad, Gujarat',
    emergency_contact: '+91 87654 32110',
    medical_history: 'None',
    created_at: '2025-01-02',
  },
  {
    id: '3',
    full_name: 'Amit Singh Rathore',
    age: 58,
    gender: 'Male',
    phone: '+91 76543 21098',
    email: 'amit.rathore@email.com',
    blood_group: 'A+',
    address: '789, Civil Lines, Jaipur, Rajasthan',
    emergency_contact: '+91 76543 21099',
    medical_history: 'Hypertension, Heart Disease',
    created_at: '2025-01-03',
  },
  {
    id: '4',
    full_name: 'Sunita Devi Gupta',
    age: 67,
    gender: 'Female',
    phone: '+91 65432 10987',
    email: 'sunita.gupta@email.com',
    blood_group: 'AB+',
    address: '321, Karol Bagh, New Delhi',
    emergency_contact: '+91 65432 10988',
    medical_history: 'Arthritis',
    created_at: '2025-01-03',
  },
  {
    id: '5',
    full_name: 'Vikram Reddy',
    age: 29,
    gender: 'Male',
    phone: '+91 54321 09876',
    email: 'vikram.reddy@email.com',
    blood_group: 'O-',
    address: '654, Banjara Hills, Hyderabad, Telangana',
    emergency_contact: '+91 54321 09877',
    medical_history: 'Asthma',
    created_at: '2025-01-04',
  },
  {
    id: '6',
    full_name: 'Meena Krishnamurthy',
    age: 41,
    gender: 'Female',
    phone: '+91 43210 98765',
    email: 'meena.k@email.com',
    blood_group: 'B-',
    address: '987, Koramangala, Bangalore, Karnataka',
    emergency_contact: '+91 43210 98766',
    medical_history: 'Thyroid disorder',
    created_at: '2025-01-05',
  },
  {
    id: '7',
    full_name: 'Arun Nair',
    age: 52,
    gender: 'Male',
    phone: '+91 32109 87654',
    email: 'arun.nair@email.com',
    blood_group: 'A-',
    address: '246, Marine Drive, Kochi, Kerala',
    emergency_contact: '+91 32109 87655',
    medical_history: 'Chronic back pain',
    created_at: '2025-01-05',
  },
  {
    id: '8',
    full_name: 'Kavita Joshi',
    age: 36,
    gender: 'Female',
    phone: '+91 21098 76543',
    email: 'kavita.joshi@email.com',
    blood_group: 'AB-',
    address: '135, FC Road, Pune, Maharashtra',
    emergency_contact: '+91 21098 76544',
    medical_history: 'Migraine',
    created_at: '2025-01-05',
  },
];

export const mockDoctors = [
  {
    id: '1',
    full_name: 'Ananya Sharma',
    specialty: 'Cardiology',
    qualification: 'MBBS, MD, DM Cardiology',
    phone: '+91 99887 76655',
    email: 'dr.ananya@hospital.com',
    experience_years: 15,
    consultation_fee: 1500,
    is_active: true,
  },
  {
    id: '2',
    full_name: 'Suresh Menon',
    specialty: 'Orthopedics',
    qualification: 'MBBS, MS Orthopedics',
    phone: '+91 88776 65544',
    email: 'dr.suresh@hospital.com',
    experience_years: 20,
    consultation_fee: 1200,
    is_active: true,
  },
  {
    id: '3',
    full_name: 'Deepika Iyer',
    specialty: 'Pediatrics',
    qualification: 'MBBS, MD Pediatrics',
    phone: '+91 77665 54433',
    email: 'dr.deepika@hospital.com',
    experience_years: 12,
    consultation_fee: 1000,
    is_active: true,
  },
  {
    id: '4',
    full_name: 'Rahul Verma',
    specialty: 'Neurology',
    qualification: 'MBBS, MD, DM Neurology',
    phone: '+91 66554 43322',
    email: 'dr.rahul@hospital.com',
    experience_years: 18,
    consultation_fee: 2000,
    is_active: true,
  },
  {
    id: '5',
    full_name: 'Pooja Agarwal',
    specialty: 'Gynecology',
    qualification: 'MBBS, MS Obstetrics & Gynecology',
    phone: '+91 55443 32211',
    email: 'dr.pooja@hospital.com',
    experience_years: 14,
    consultation_fee: 1300,
    is_active: true,
  },
  {
    id: '6',
    full_name: 'Manoj Tiwari',
    specialty: 'General Medicine',
    qualification: 'MBBS, MD Internal Medicine',
    phone: '+91 44332 21100',
    email: 'dr.manoj@hospital.com',
    experience_years: 10,
    consultation_fee: 800,
    is_active: true,
  },
  {
    id: '7',
    full_name: 'Lakshmi Venkatesh',
    specialty: 'Dermatology',
    qualification: 'MBBS, MD Dermatology',
    phone: '+91 33221 10099',
    email: 'dr.lakshmi@hospital.com',
    experience_years: 8,
    consultation_fee: 1100,
    is_active: true,
  },
  {
    id: '8',
    full_name: 'Sanjay Kapoor',
    specialty: 'ENT',
    qualification: 'MBBS, MS ENT',
    phone: '+91 22110 09988',
    email: 'dr.sanjay@hospital.com',
    experience_years: 16,
    consultation_fee: 900,
    is_active: false,
  },
];

export const mockWards = [
  {
    id: '1',
    name: 'General Ward A',
    ward_type: 'General',
    total_beds: 20,
    available_beds: 8,
    floor: 1,
    description: 'General ward for male patients',
  },
  {
    id: '2',
    name: 'General Ward B',
    ward_type: 'General',
    total_beds: 20,
    available_beds: 5,
    floor: 1,
    description: 'General ward for female patients',
  },
  {
    id: '3',
    name: 'ICU',
    ward_type: 'Intensive Care',
    total_beds: 10,
    available_beds: 3,
    floor: 2,
    description: 'Intensive Care Unit',
  },
  {
    id: '4',
    name: 'Pediatric Ward',
    ward_type: 'Pediatric',
    total_beds: 15,
    available_beds: 7,
    floor: 3,
    description: 'Ward for children',
  },
  {
    id: '5',
    name: 'Maternity Ward',
    ward_type: 'Maternity',
    total_beds: 12,
    available_beds: 4,
    floor: 3,
    description: 'Maternity and delivery ward',
  },
];

export const mockRooms = [
  { id: '1', ward_id: '1', room_number: '101', room_type: 'General', total_beds: 4, available_beds: 2, daily_rate: 500, is_available: true },
  { id: '2', ward_id: '1', room_number: '102', room_type: 'General', total_beds: 4, available_beds: 1, daily_rate: 500, is_available: true },
  { id: '3', ward_id: '1', room_number: '103', room_type: 'Semi-Private', total_beds: 2, available_beds: 2, daily_rate: 1000, is_available: true },
  { id: '4', ward_id: '2', room_number: '201', room_type: 'General', total_beds: 4, available_beds: 0, daily_rate: 500, is_available: false },
  { id: '5', ward_id: '2', room_number: '202', room_type: 'Private', total_beds: 1, available_beds: 1, daily_rate: 2500, is_available: true },
  { id: '6', ward_id: '3', room_number: 'ICU-01', room_type: 'ICU', total_beds: 2, available_beds: 1, daily_rate: 5000, is_available: true },
  { id: '7', ward_id: '3', room_number: 'ICU-02', room_type: 'ICU', total_beds: 2, available_beds: 0, daily_rate: 5000, is_available: false },
  { id: '8', ward_id: '4', room_number: '301', room_type: 'General', total_beds: 3, available_beds: 2, daily_rate: 600, is_available: true },
  { id: '9', ward_id: '4', room_number: '302', room_type: 'General', total_beds: 3, available_beds: 3, daily_rate: 600, is_available: true },
  { id: '10', ward_id: '5', room_number: '401', room_type: 'Private', total_beds: 1, available_beds: 0, daily_rate: 3000, is_available: false },
  { id: '11', ward_id: '5', room_number: '402', room_type: 'Semi-Private', total_beds: 2, available_beds: 1, daily_rate: 1800, is_available: true },
];

export const mockAppointments = [
  {
    id: '1',
    appointment_date: '2026-01-05',
    appointment_time: '09:00',
    status: 'scheduled',
    notes: 'Regular checkup',
    patient_id: '1',
    doctor_id: '1',
  },
  {
    id: '2',
    appointment_date: '2026-01-05',
    appointment_time: '10:30',
    status: 'confirmed',
    notes: 'Follow-up for knee pain',
    patient_id: '3',
    doctor_id: '2',
  },
  {
    id: '3',
    appointment_date: '2026-01-05',
    appointment_time: '11:00',
    status: 'in-progress',
    notes: 'Child vaccination',
    patient_id: '2',
    doctor_id: '3',
  },
  {
    id: '4',
    appointment_date: '2026-01-05',
    appointment_time: '14:00',
    status: 'completed',
    notes: 'Headache consultation',
    patient_id: '4',
    doctor_id: '4',
  },
  {
    id: '5',
    appointment_date: '2026-01-06',
    appointment_time: '09:30',
    status: 'scheduled',
    notes: 'Prenatal checkup',
    patient_id: '6',
    doctor_id: '5',
  },
  {
    id: '6',
    appointment_date: '2026-01-06',
    appointment_time: '11:00',
    status: 'scheduled',
    notes: 'General health checkup',
    patient_id: '5',
    doctor_id: '6',
  },
  {
    id: '7',
    appointment_date: '2026-01-04',
    appointment_time: '15:00',
    status: 'completed',
    notes: 'Skin allergy treatment',
    patient_id: '8',
    doctor_id: '7',
  },
  {
    id: '8',
    appointment_date: '2026-01-04',
    appointment_time: '16:30',
    status: 'cancelled',
    notes: 'ENT consultation',
    patient_id: '7',
    doctor_id: '8',
  },
];
