export const labTests = [
  { 
    id: '1', 
    testCode: 'CBC', 
    testName: 'Complete Blood Count', 
    category: 'Hematology', 
    normalRange: 'See detailed report', 
    unit: '',
    price: 45,
    specimenType: 'Blood',
    turnaroundTime: '4 hours',
    isActive: true,
    parameters: [
      { id: 'cbc-1', name: 'WBC', unit: 'x10³/µL', normalRangeMin: 4.5, normalRangeMax: 11.0, criticalMin: 2.0, criticalMax: 30.0 },
      { id: 'cbc-2', name: 'RBC', unit: 'x10⁶/µL', normalRangeMin: 4.5, normalRangeMax: 5.5, criticalMin: 2.0, criticalMax: 8.0 },
      { id: 'cbc-3', name: 'Hemoglobin', unit: 'g/dL', normalRangeMin: 12.0, normalRangeMax: 17.0, criticalMin: 7.0, criticalMax: 20.0 },
      { id: 'cbc-4', name: 'Hematocrit', unit: '%', normalRangeMin: 36, normalRangeMax: 50, criticalMin: 20, criticalMax: 60 },
      { id: 'cbc-5', name: 'Platelets', unit: 'x10³/µL', normalRangeMin: 150, normalRangeMax: 400, criticalMin: 50, criticalMax: 1000 },
    ],
    instructions: 'Fasting not required. Avoid strenuous exercise before test.'
  },
  { 
    id: '2', 
    testCode: 'BMP', 
    testName: 'Basic Metabolic Panel', 
    category: 'Chemistry', 
    normalRange: 'See detailed report', 
    unit: '',
    price: 65,
    specimenType: 'Blood',
    turnaroundTime: '6 hours',
    isActive: true,
    parameters: [
      { id: 'bmp-1', name: 'Glucose', unit: 'mg/dL', normalRangeMin: 70, normalRangeMax: 100, criticalMin: 40, criticalMax: 500 },
      { id: 'bmp-2', name: 'Sodium', unit: 'mEq/L', normalRangeMin: 136, normalRangeMax: 145, criticalMin: 120, criticalMax: 160 },
      { id: 'bmp-3', name: 'Potassium', unit: 'mEq/L', normalRangeMin: 3.5, normalRangeMax: 5.0, criticalMin: 2.5, criticalMax: 6.5 },
      { id: 'bmp-4', name: 'Chloride', unit: 'mEq/L', normalRangeMin: 98, normalRangeMax: 106 },
      { id: 'bmp-5', name: 'Creatinine', unit: 'mg/dL', normalRangeMin: 0.7, normalRangeMax: 1.3, criticalMax: 10.0 },
      { id: 'bmp-6', name: 'BUN', unit: 'mg/dL', normalRangeMin: 7, normalRangeMax: 20, criticalMax: 100 },
    ],
    instructions: 'Fasting for 8-12 hours recommended.'
  },
  { 
    id: '3', 
    testCode: 'LFT', 
    testName: 'Liver Function Test', 
    category: 'Chemistry', 
    normalRange: 'See detailed report', 
    unit: '',
    price: 75,
    specimenType: 'Blood',
    turnaroundTime: '6 hours',
    isActive: true,
    parameters: [
      { id: 'lft-1', name: 'ALT', unit: 'U/L', normalRangeMin: 7, normalRangeMax: 56 },
      { id: 'lft-2', name: 'AST', unit: 'U/L', normalRangeMin: 10, normalRangeMax: 40 },
      { id: 'lft-3', name: 'ALP', unit: 'U/L', normalRangeMin: 44, normalRangeMax: 147 },
      { id: 'lft-4', name: 'Total Bilirubin', unit: 'mg/dL', normalRangeMin: 0.1, normalRangeMax: 1.2, criticalMax: 15.0 },
      { id: 'lft-5', name: 'Albumin', unit: 'g/dL', normalRangeMin: 3.5, normalRangeMax: 5.0 },
    ],
    instructions: 'Fasting for 8-12 hours recommended. Avoid alcohol 24 hours before.'
  },
  { 
    id: '4', 
    testCode: 'TSH', 
    testName: 'Thyroid Stimulating Hormone', 
    category: 'Endocrine', 
    normalRange: '0.4-4.0', 
    unit: 'mIU/L',
    price: 55,
    specimenType: 'Blood',
    turnaroundTime: '24 hours',
    isActive: true,
    parameters: [
      { id: 'tsh-1', name: 'TSH', unit: 'mIU/L', normalRangeMin: 0.4, normalRangeMax: 4.0 },
    ],
    instructions: 'Best collected in the morning. No fasting required.'
  },
  { 
    id: '5', 
    testCode: 'HbA1c', 
    testName: 'Glycated Hemoglobin', 
    category: 'Chemistry', 
    normalRange: '4.0-5.6', 
    unit: '%',
    price: 50,
    specimenType: 'Blood',
    turnaroundTime: '24 hours',
    isActive: true,
    parameters: [
      { id: 'hba1c-1', name: 'HbA1c', unit: '%', normalRangeMin: 4.0, normalRangeMax: 5.6 },
    ],
    instructions: 'No fasting required.'
  },
  { 
    id: '6', 
    testCode: 'UA', 
    testName: 'Urinalysis', 
    category: 'Urinalysis', 
    normalRange: 'See detailed report', 
    unit: '',
    price: 25,
    specimenType: 'Urine',
    turnaroundTime: '2 hours',
    isActive: true,
    parameters: [
      { id: 'ua-1', name: 'pH', unit: '', normalRangeMin: 4.5, normalRangeMax: 8.0 },
      { id: 'ua-2', name: 'Specific Gravity', unit: '', normalRangeMin: 1.005, normalRangeMax: 1.030 },
      { id: 'ua-3', name: 'Protein', unit: '', normalRangeText: 'Negative' },
      { id: 'ua-4', name: 'Glucose', unit: '', normalRangeText: 'Negative' },
      { id: 'ua-5', name: 'Blood', unit: '', normalRangeText: 'Negative' },
    ],
    instructions: 'Midstream clean-catch specimen required.'
  },
  { 
    id: '7', 
    testCode: 'PT/INR', 
    testName: 'Prothrombin Time/INR', 
    category: 'Coagulation', 
    normalRange: '11-13.5 / 0.8-1.2', 
    unit: 'sec / ratio',
    price: 40,
    specimenType: 'Blood',
    turnaroundTime: '4 hours',
    isActive: true,
    parameters: [
      { id: 'pt-1', name: 'PT', unit: 'sec', normalRangeMin: 11, normalRangeMax: 13.5, criticalMax: 30 },
      { id: 'pt-2', name: 'INR', unit: 'ratio', normalRangeMin: 0.8, normalRangeMax: 1.2, criticalMax: 5.0 },
    ],
    instructions: 'Note any anticoagulant medications.'
  },
  { 
    id: '8', 
    testCode: 'LIPID', 
    testName: 'Lipid Panel', 
    category: 'Chemistry', 
    normalRange: 'See detailed report', 
    unit: '',
    price: 60,
    specimenType: 'Blood',
    turnaroundTime: '6 hours',
    isActive: true,
    parameters: [
      { id: 'lipid-1', name: 'Total Cholesterol', unit: 'mg/dL', normalRangeMax: 200 },
      { id: 'lipid-2', name: 'LDL', unit: 'mg/dL', normalRangeMax: 100 },
      { id: 'lipid-3', name: 'HDL', unit: 'mg/dL', normalRangeMin: 40 },
      { id: 'lipid-4', name: 'Triglycerides', unit: 'mg/dL', normalRangeMax: 150, criticalMax: 1000 },
    ],
    instructions: 'Fasting for 9-12 hours required.'
  },
];

export const patients = [
  { id: '1', name: 'John Anderson', age: 45, gender: 'male', contact: '+1-555-0101', mrn: 'MRN-2024-001' },
  { id: '2', name: 'Sarah Mitchell', age: 32, gender: 'female', contact: '+1-555-0102', mrn: 'MRN-2024-002' },
  { id: '3', name: 'Robert Chen', age: 58, gender: 'male', contact: '+1-555-0103', mrn: 'MRN-2024-003' },
  { id: '4', name: 'Emily Davis', age: 27, gender: 'female', contact: '+1-555-0104', mrn: 'MRN-2024-004' },
  { id: '5', name: 'Michael Thompson', age: 65, gender: 'male', contact: '+1-555-0105', mrn: 'MRN-2024-005' },
];

export const initialLabOrders = [
  {
    id: '1',
    orderId: 'LAB-2024-0001',
    patient: patients[0],
    tests: [labTests[0]],
    specimenId: 'SPEC-001',
    specimenTypes: ['Blood'],
    specimenTracking: {
      specimenId: 'SPEC-001',
      barcode: 'BC-ABC123-XY01',
      type: 'Blood',
      collectedAt: new Date('2024-01-15T08:30:00'),
      collectedBy: 'Phlebotomist: Jane Doe',
      receivedAt: new Date('2024-01-15T08:45:00'),
      receivedBy: 'Lab Tech: John Smith',
      status: 'stored',
      storageLocation: 'Refrigerator A, Rack 3',
      chainOfCustody: [
        { id: '1', timestamp: new Date('2024-01-15T08:30:00'), action: 'Specimen collected', performedBy: 'Phlebotomist: Jane Doe' },
        { id: '2', timestamp: new Date('2024-01-15T08:45:00'), action: 'Received at lab', performedBy: 'Lab Tech: John Smith' },
        { id: '3', timestamp: new Date('2024-01-15T09:00:00'), action: 'Processing started', performedBy: 'Lab Tech: John Smith' },
        { id: '4', timestamp: new Date('2024-01-15T14:30:00'), action: 'Stored for archive', performedBy: 'Lab Tech: Maria Santos' },
      ]
    },
    collectedAt: new Date('2024-01-15T08:30:00'),
    status: 'completed',
    priority: 'routine',
    orderedBy: 'Dr. Williams',
    result: 'WBC: 7.5, RBC: 4.8, Hgb: 14.2, Hct: 42%, Plt: 250',
    resultNote: 'All values within normal range',
    completedAt: new Date('2024-01-15T14:30:00'),
    technicianName: 'Lab Tech: Maria Santos',
  },
  {
    id: '2',
    orderId: 'LAB-2024-0002',
    patient: patients[1],
    tests: [labTests[3]],
    specimenId: 'SPEC-002',
    specimenTypes: ['Blood'],
    specimenTracking: {
      specimenId: 'SPEC-002',
      barcode: 'BC-DEF456-ZW02',
      type: 'Blood',
      collectedAt: new Date('2024-01-15T09:15:00'),
      collectedBy: 'Phlebotomist: Jane Doe',
      receivedAt: new Date('2024-01-15T09:30:00'),
      receivedBy: 'Lab Tech: John Smith',
      status: 'processing',
      chainOfCustody: [
        { id: '1', timestamp: new Date('2024-01-15T09:15:00'), action: 'Specimen collected', performedBy: 'Phlebotomist: Jane Doe' },
        { id: '2', timestamp: new Date('2024-01-15T09:30:00'), action: 'Received at lab', performedBy: 'Lab Tech: John Smith' },
      ]
    },
    collectedAt: new Date('2024-01-15T09:15:00'),
    status: 'processing',
    priority: 'routine',
    orderedBy: 'Dr. Johnson',
  },
  {
    id: '3',
    orderId: 'LAB-2024-0003',
    patient: patients[2],
    tests: [labTests[4]],
    specimenId: 'SPEC-003',
    specimenTypes: ['Blood'],
    specimenTracking: {
      specimenId: 'SPEC-003',
      barcode: 'BC-GHI789-UV03',
      type: 'Blood',
      collectedAt: new Date('2024-01-15T10:00:00'),
      collectedBy: 'Phlebotomist: Mark Wilson',
      status: 'collected',
      chainOfCustody: [
        { id: '1', timestamp: new Date('2024-01-15T10:00:00'), action: 'Specimen collected', performedBy: 'Phlebotomist: Mark Wilson' },
      ]
    },
    collectedAt: new Date('2024-01-15T10:00:00'),
    status: 'pending',
    priority: 'urgent',
    orderedBy: 'Dr. Martinez',
  },
  {
    id: '4',
    orderId: 'LAB-2024-0004',
    patient: patients[3],
    tests: [labTests[5]],
    specimenId: 'SPEC-004',
    specimenTypes: ['Urine'],
    specimenTracking: {
      specimenId: 'SPEC-004',
      barcode: 'BC-JKL012-ST04',
      type: 'Urine',
      collectedAt: new Date('2024-01-15T10:30:00'),
      collectedBy: 'Self-collected',
      status: 'collected',
      chainOfCustody: [
        { id: '1', timestamp: new Date('2024-01-15T10:30:00'), action: 'Specimen collected', performedBy: 'Self-collected' },
      ]
    },
    collectedAt: new Date('2024-01-15T10:30:00'),
    status: 'pending',
    priority: 'routine',
    orderedBy: 'Dr. Williams',
  },
  {
    id: '5',
    orderId: 'LAB-2024-0005',
    patient: patients[4],
    tests: [labTests[7]],
    specimenId: 'SPEC-005',
    specimenTypes: ['Blood'],
    specimenTracking: {
      specimenId: 'SPEC-005',
      barcode: 'BC-MNO345-QR05',
      type: 'Blood',
      collectedAt: new Date('2024-01-15T07:45:00'),
      collectedBy: 'Phlebotomist: Jane Doe',
      receivedAt: new Date('2024-01-15T08:00:00'),
      receivedBy: 'Lab Tech: John Smith',
      status: 'stored',
      storageLocation: 'Refrigerator B, Rack 1',
      chainOfCustody: [
        { id: '1', timestamp: new Date('2024-01-15T07:45:00'), action: 'Specimen collected', performedBy: 'Phlebotomist: Jane Doe' },
        { id: '2', timestamp: new Date('2024-01-15T08:00:00'), action: 'Received at lab', performedBy: 'Lab Tech: John Smith' },
        { id: '3', timestamp: new Date('2024-01-15T11:00:00'), action: 'Stored for archive', performedBy: 'Lab Tech: James Wilson' },
      ]
    },
    collectedAt: new Date('2024-01-15T07:45:00'),
    status: 'completed',
    priority: 'stat',
    orderedBy: 'Dr. Brown',
    result: 'Total Cholesterol: 185, LDL: 110, HDL: 55, Triglycerides: 100',
    resultNote: 'Borderline LDL levels - lifestyle modifications recommended',
    completedAt: new Date('2024-01-15T11:00:00'),
    technicianName: 'Lab Tech: James Wilson',
  },
];

export const initialQCSamples = [
  {
    id: 'qc-1',
    lotNumber: 'QC-LOT-2024-001',
    testId: '1',
    testName: 'Complete Blood Count',
    level: 'normal',
    expectedValue: 7.5,
    acceptableRange: { min: 6.5, max: 8.5 },
    results: [
      { id: 'qcr-1', qcSampleId: 'qc-1', value: 7.3, performedAt: new Date('2024-01-14T08:00:00'), performedBy: 'Lab Tech: Maria Santos', isAccepted: true },
      { id: 'qcr-2', qcSampleId: 'qc-1', value: 7.6, performedAt: new Date('2024-01-15T08:00:00'), performedBy: 'Lab Tech: John Smith', isAccepted: true },
    ],
    expiryDate: new Date('2024-06-15'),
    isActive: true,
  },
  {
    id: 'qc-2',
    lotNumber: 'QC-LOT-2024-002',
    testId: '2',
    testName: 'Basic Metabolic Panel',
    level: 'low',
    expectedValue: 75,
    acceptableRange: { min: 70, max: 80 },
    results: [
      { id: 'qcr-3', qcSampleId: 'qc-2', value: 74, performedAt: new Date('2024-01-14T09:00:00'), performedBy: 'Lab Tech: James Wilson', isAccepted: true },
      { id: 'qcr-4', qcSampleId: 'qc-2', value: 82, performedAt: new Date('2024-01-15T09:00:00'), performedBy: 'Lab Tech: Maria Santos', isAccepted: false, westgardViolation: '1-2s' },
    ],
    expiryDate: new Date('2024-06-20'),
    isActive: true,
  },
  {
    id: 'qc-3',
    lotNumber: 'QC-LOT-2024-003',
    testId: '2',
    testName: 'Basic Metabolic Panel',
    level: 'high',
    expectedValue: 110,
    acceptableRange: { min: 105, max: 115 },
    results: [
      { id: 'qcr-5', qcSampleId: 'qc-3', value: 108, performedAt: new Date('2024-01-14T09:00:00'), performedBy: 'Lab Tech: James Wilson', isAccepted: true },
    ],
    expiryDate: new Date('2024-06-20'),
    isActive: true,
  },
];

export const initialCriticalAlerts = [];

export const calculateStats = (orders) => {
  return {
    total: orders.length,
    pending: orders.filter(o => o.status === 'pending').length,
    processing: orders.filter(o => o.status === 'processing').length,
    completed: orders.filter(o => o.status === 'completed').length,
    urgent: orders.filter(o => o.priority === 'urgent' || o.priority === 'stat').length,
  };
};
