const createDate = (hoursAgo) => {
  const date = new Date();
  date.setHours(date.getHours() - hoursAgo);
  return date;
};

export const mockOPDPatients = {
  registration: [
    {
      id: 'p10',
      name: 'Anjali Gupta',
      mrn: 'MRN-2024-020',
      age: 32,
      gender: 'Female',
      stageEnteredAt: createDate(0.1),
      status: 'pending',
      workflowType: 'opd',
    },
    {
      id: 'p11',
      name: 'Deepak Kumar',
      mrn: 'MRN-2024-021',
      age: 55,
      gender: 'Male',
      stageEnteredAt: createDate(0.2),
      status: 'pending',
      workflowType: 'opd',
    },
  ],
  triage: [
    {
      id: 'p1',
      name: 'Vikram Joshi',
      mrn: 'MRN-2024-005',
      age: 28,
      gender: 'Male',
      stageEnteredAt: createDate(2),
      status: 'in-progress',
      workflowType: 'opd',
    },
    {
      id: 'p12',
      name: 'Priya Sharma',
      mrn: 'MRN-2024-022',
      age: 45,
      gender: 'Female',
      stageEnteredAt: createDate(1.5),
      status: 'pending',
      priority: 'urgent',
      workflowType: 'opd',
    },
  ],
  waiting: [
    {
      id: 'p13',
      name: 'Rajesh Malhotra',
      mrn: 'MRN-2024-023',
      age: 62,
      gender: 'Male',
      doctor: 'Dr. Priya Patel',
      stageEnteredAt: createDate(0.75),
      status: 'pending',
      workflowType: 'opd',
    },
    {
      id: 'p14',
      name: 'Sunita Devi',
      mrn: 'MRN-2024-024',
      age: 38,
      gender: 'Female',
      doctor: 'Dr. Sunita Rao',
      stageEnteredAt: createDate(0.5),
      status: 'pending',
      workflowType: 'opd',
    },
    {
      id: 'p15',
      name: 'Mohammed Ali',
      mrn: 'MRN-2024-025',
      age: 50,
      gender: 'Male',
      doctor: 'Dr. Rajesh Kumar',
      stageEnteredAt: createDate(0.3),
      status: 'pending',
      priority: 'urgent',
      workflowType: 'opd',
    },
  ],
  consultation: [
    {
      id: 'p2',
      name: 'Rahul Sharma',
      mrn: 'MRN-2024-001',
      age: 45,
      gender: 'Male',
      doctor: 'Dr. Priya Patel',
      stageEnteredAt: createDate(1),
      status: 'in-progress',
      workflowType: 'opd',
    },
    {
      id: 'p16',
      name: 'Kavita Singh',
      mrn: 'MRN-2024-026',
      age: 29,
      gender: 'Female',
      doctor: 'Dr. Sunita Rao',
      stageEnteredAt: createDate(0.5),
      status: 'in-progress',
      workflowType: 'opd',
    },
  ],
  investigation: [
    {
      id: 'p3',
      name: 'Arun Mehta',
      mrn: 'MRN-2024-003',
      age: 58,
      gender: 'Male',
      doctor: 'Dr. Sunita Rao',
      stageEnteredAt: createDate(0.5),
      status: 'pending',
      priority: 'urgent',
      workflowType: 'opd',
    },
    {
      id: 'p17',
      name: 'Neha Agarwal',
      mrn: 'MRN-2024-027',
      age: 34,
      gender: 'Female',
      doctor: 'Dr. Priya Patel',
      stageEnteredAt: createDate(1.2),
      status: 'in-progress',
      workflowType: 'opd',
    },
    {
      id: 'p18',
      name: 'Sanjay Verma',
      mrn: 'MRN-2024-028',
      age: 67,
      gender: 'Male',
      doctor: 'Dr. Rajesh Kumar',
      stageEnteredAt: createDate(2),
      status: 'critical',
      priority: 'critical',
      workflowType: 'opd',
    },
  ],
  pharmacy: [
    {
      id: 'p4',
      name: 'Kiran Singh',
      mrn: 'MRN-2024-007',
      age: 42,
      gender: 'Male',
      doctor: 'Dr. Priya Patel',
      stageEnteredAt: createDate(0.25),
      status: 'in-progress',
      workflowType: 'opd',
    },
    {
      id: 'p19',
      name: 'Rekha Jain',
      mrn: 'MRN-2024-029',
      age: 51,
      gender: 'Female',
      doctor: 'Dr. Anita Desai',
      stageEnteredAt: createDate(0.4),
      status: 'pending',
      workflowType: 'opd',
    },
  ],
  followup: [
    {
      id: 'p20',
      name: 'Amit Patel',
      mrn: 'MRN-2024-030',
      age: 40,
      gender: 'Male',
      doctor: 'Dr. Priya Patel',
      stageEnteredAt: createDate(0.1),
      status: 'completed',
      workflowType: 'opd',
    },
    {
      id: 'p21',
      name: 'Pooja Reddy',
      mrn: 'MRN-2024-031',
      age: 26,
      gender: 'Female',
      doctor: 'Dr. Sunita Rao',
      stageEnteredAt: createDate(0.2),
      status: 'completed',
      workflowType: 'opd',
    },
  ],
};

export const mockIPDPatients = {
  admission: [
    {
      id: 'ip1',
      name: 'Meera Kapoor',
      mrn: 'MRN-2024-010',
      age: 65,
      gender: 'Female',
      doctor: 'Dr. Rajesh Kumar',
      stageEnteredAt: createDate(4),
      status: 'in-progress',
      priority: 'urgent',
      workflowType: 'ipd',
    },
    {
      id: 'ip10',
      name: 'Harish Chandra',
      mrn: 'MRN-2024-040',
      age: 72,
      gender: 'Male',
      doctor: 'Dr. Anita Desai',
      stageEnteredAt: createDate(2),
      status: 'pending',
      priority: 'critical',
      workflowType: 'ipd',
    },
  ],
  'ward-assignment': [
    {
      id: 'ip11',
      name: 'Fatima Begum',
      mrn: 'MRN-2024-041',
      age: 58,
      gender: 'Female',
      doctor: 'Dr. Rajesh Kumar',
      stageEnteredAt: createDate(3),
      status: 'in-progress',
      workflowType: 'ipd',
    },
    {
      id: 'ip12',
      name: 'Ravi Shankar',
      mrn: 'MRN-2024-042',
      age: 45,
      gender: 'Male',
      doctor: 'Dr. Priya Patel',
      stageEnteredAt: createDate(2.5),
      status: 'pending',
      workflowType: 'ipd',
    },
  ],
  treatment: [
    {
      id: 'ip2',
      name: 'Suresh Reddy',
      mrn: 'MRN-2024-008',
      age: 52,
      gender: 'Male',
      doctor: 'Dr. Anita Desai',
      stageEnteredAt: createDate(24),
      status: 'in-progress',
      workflowType: 'ipd',
    },
    {
      id: 'ip3',
      name: 'Lakshmi Nair',
      mrn: 'MRN-2024-009',
      age: 38,
      gender: 'Female',
      doctor: 'Dr. Rajesh Kumar',
      stageEnteredAt: createDate(48),
      status: 'critical',
      priority: 'critical',
      workflowType: 'ipd',
    },
    {
      id: 'ip13',
      name: 'Vijay Prakash',
      mrn: 'MRN-2024-043',
      age: 61,
      gender: 'Male',
      doctor: 'Dr. Sunita Rao',
      stageEnteredAt: createDate(36),
      status: 'in-progress',
      workflowType: 'ipd',
    },
  ],
  monitoring: [
    {
      id: 'ip4',
      name: 'Gopal Verma',
      mrn: 'MRN-2024-011',
      age: 70,
      gender: 'Male',
      doctor: 'Dr. Anita Desai',
      stageEnteredAt: createDate(12),
      status: 'pending',
      workflowType: 'ipd',
    },
    {
      id: 'ip14',
      name: 'Sarita Mishra',
      mrn: 'MRN-2024-044',
      age: 55,
      gender: 'Female',
      doctor: 'Dr. Rajesh Kumar',
      stageEnteredAt: createDate(18),
      status: 'in-progress',
      workflowType: 'ipd',
    },
    {
      id: 'ip15',
      name: 'Ramesh Gupta',
      mrn: 'MRN-2024-045',
      age: 68,
      gender: 'Male',
      doctor: 'Dr. Priya Patel',
      stageEnteredAt: createDate(8),
      status: 'in-progress',
      priority: 'urgent',
      workflowType: 'ipd',
    },
  ],
  'discharge-planning': [
    {
      id: 'ip16',
      name: 'Kamala Devi',
      mrn: 'MRN-2024-046',
      age: 49,
      gender: 'Female',
      doctor: 'Dr. Anita Desai',
      stageEnteredAt: createDate(6),
      status: 'in-progress',
      workflowType: 'ipd',
    },
    {
      id: 'ip17',
      name: 'Ashok Sharma',
      mrn: 'MRN-2024-047',
      age: 56,
      gender: 'Male',
      doctor: 'Dr. Sunita Rao',
      stageEnteredAt: createDate(4),
      status: 'pending',
      workflowType: 'ipd',
    },
  ],
  discharge: [
    {
      id: 'ip18',
      name: 'Usha Rani',
      mrn: 'MRN-2024-048',
      age: 42,
      gender: 'Female',
      doctor: 'Dr. Rajesh Kumar',
      stageEnteredAt: createDate(1),
      status: 'completed',
      workflowType: 'ipd',
    },
    {
      id: 'ip19',
      name: 'Manoj Kumar',
      mrn: 'MRN-2024-049',
      age: 35,
      gender: 'Male',
      doctor: 'Dr. Priya Patel',
      stageEnteredAt: createDate(0.5),
      status: 'completed',
      workflowType: 'ipd',
    },
  ],
};
