// Mock data for categories and tags

export const mockCategories = [
  {
    id: 'cat1',
    name: 'Primary Care',
    description: 'General primary care related items',
    icon: 'Stethoscope',
    color: 'blue',
    entityTypes: ['appointment', 'patient'],
    parentId: null,
    itemCount: 45,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'cat2',
    name: 'Emergency',
    description: 'Emergency and urgent care items',
    icon: 'AlertCircle',
    color: 'red',
    entityTypes: ['appointment', 'patient'],
    parentId: null,
    itemCount: 12,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'cat3',
    name: 'Chronic Care',
    description: 'Long-term chronic condition management',
    icon: 'Heart',
    color: 'purple',
    entityTypes: ['patient', 'prescription'],
    parentId: null,
    itemCount: 28,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'cat4',
    name: 'Pediatrics',
    description: 'Child and adolescent care',
    icon: 'Users',
    color: 'green',
    entityTypes: ['appointment', 'patient'],
    parentId: 'cat1',
    itemCount: 15,
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'cat5',
    name: 'Cardiology',
    description: 'Heart and cardiovascular care',
    icon: 'Activity',
    color: 'rose',
    entityTypes: ['appointment', 'patient', 'prescription'],
    parentId: 'cat3',
    itemCount: 8,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'cat6',
    name: 'Lab Results',
    description: 'Laboratory test results and reports',
    icon: 'FileText',
    color: 'amber',
    entityTypes: ['document'],
    parentId: null,
    itemCount: 120,
    createdAt: new Date('2024-03-01'),
  },
];

export const mockTags = [
  {
    id: 'tag1',
    name: 'Urgent',
    description: 'Requires immediate attention',
    color: 'red',
    entityTypes: ['appointment', 'patient'],
    usageCount: 34,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'tag2',
    name: 'Follow-up Required',
    description: 'Needs follow-up appointment or action',
    color: 'orange',
    entityTypes: ['appointment', 'patient', 'prescription'],
    usageCount: 56,
    createdAt: new Date('2024-01-12'),
  },
  {
    id: 'tag3',
    name: 'VIP',
    description: 'High-priority patient',
    color: 'purple',
    entityTypes: ['patient'],
    usageCount: 8,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'tag4',
    name: 'Insurance Pending',
    description: 'Awaiting insurance verification',
    color: 'amber',
    entityTypes: ['appointment', 'patient'],
    usageCount: 23,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'tag5',
    name: 'New Patient',
    description: 'First-time patient',
    color: 'green',
    entityTypes: ['patient', 'appointment'],
    usageCount: 89,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'tag6',
    name: 'Telemedicine',
    description: 'Virtual/remote appointment',
    color: 'blue',
    entityTypes: ['appointment'],
    usageCount: 67,
    createdAt: new Date('2024-02-05'),
  },
  {
    id: 'tag7',
    name: 'Controlled Substance',
    description: 'Prescription for controlled medication',
    color: 'rose',
    entityTypes: ['prescription'],
    usageCount: 12,
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'tag8',
    name: 'Allergy Alert',
    description: 'Patient has known allergies',
    color: 'red',
    entityTypes: ['patient', 'prescription'],
    usageCount: 45,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'tag9',
    name: 'Pediatric',
    description: 'Child patient',
    color: 'cyan',
    entityTypes: ['patient', 'appointment', 'prescription'],
    usageCount: 34,
    createdAt: new Date('2024-02-20'),
  },
  {
    id: 'tag10',
    name: 'Geriatric',
    description: 'Elderly patient considerations',
    color: 'teal',
    entityTypes: ['patient', 'appointment', 'prescription'],
    usageCount: 28,
    createdAt: new Date('2024-03-01'),
  },
];
