export const mockPatients = [
  {
    id: "P-2024-001",
    firstName: "John",
    lastName: "Smith",
    dateOfBirth: "1985-03-15",
    gender: "male",
    email: "john.smith@email.com",
    phone: "(555) 123-4567",
    address: "123 Oak Street, Boston, MA 02101",
    bloodType: "A+",
    emergencyContact: {
      name: "Sarah Smith",
      phone: "(555) 987-6543",
      relationship: "Spouse",
    },
    insuranceProvider: "Blue Cross Blue Shield",
    insuranceNumber: "BCBS-789456123",
    medicalHistory: [
      {
        id: "mh-1",
        date: "2024-12-28",
        type: "checkup",
        title: "Annual Physical Examination",
        description: "Routine annual checkup. All vitals normal. Recommended continued exercise regimen.",
        doctor: "Dr. Sarah Johnson",
      },
      {
        id: "mh-2",
        date: "2024-06-15",
        type: "diagnosis",
        title: "Mild Hypertension",
        description: "Diagnosed with stage 1 hypertension. Started on lifestyle modifications.",
        doctor: "Dr. Sarah Johnson",
      },
      {
        id: "mh-3",
        date: "2023-11-20",
        type: "vaccination",
        title: "Flu Vaccination",
        description: "Annual influenza vaccine administered.",
        doctor: "Nurse Patricia",
      },
    ],
    allergies: ["Penicillin", "Shellfish"],
    currentMedications: ["Lisinopril 10mg daily"],
    status: "active",
    assignedDoctor: "Dr. Sarah Johnson",
    department: "Internal Medicine",
  },
  {
    id: "P-2024-002",
    firstName: "Maria",
    lastName: "Garcia",
    dateOfBirth: "1990-07-22",
    gender: "female",
    email: "maria.garcia@email.com",
    phone: "(555) 234-5678",
    address: "456 Maple Avenue, Boston, MA 02102",
    bloodType: "O+",
    emergencyContact: {
      name: "Carlos Garcia",
      phone: "(555) 876-5432",
      relationship: "Brother",
    },
    insuranceProvider: "Aetna",
    insuranceNumber: "AET-456789123",
    medicalHistory: [
      {
        id: "mh-4",
        date: "2024-12-26",
        type: "treatment",
        title: "Respiratory Infection Treatment",
        description: "Prescribed Amoxicillin for bacterial respiratory infection.",
        doctor: "Dr. Emily Chen",
      },
      {
        id: "mh-5",
        date: "2024-09-10",
        type: "checkup",
        title: "Women's Health Checkup",
        description: "Annual women's health examination. All results normal.",
        doctor: "Dr. Emily Chen",
      },
    ],
    allergies: ["Latex"],
    currentMedications: ["Amoxicillin 500mg (current course)", "Vitamin D 1000IU"],
    status: "active",
    assignedDoctor: "Dr. Emily Chen",
    department: "General Practice",
  },
  {
    id: "P-2024-003",
    firstName: "Robert",
    lastName: "Williams",
    dateOfBirth: "1978-11-08",
    gender: "male",
    email: "robert.williams@email.com",
    phone: "(555) 345-6789",
    address: "789 Pine Road, Cambridge, MA 02139",
    bloodType: "B+",
    emergencyContact: {
      name: "Linda Williams",
      phone: "(555) 765-4321",
      relationship: "Wife",
    },
    insuranceProvider: "UnitedHealthcare",
    insuranceNumber: "UHC-123456789",
    medicalHistory: [
      {
        id: "mh-6",
        date: "2024-12-25",
        type: "diagnosis",
        title: "Chest X-Ray Review",
        description: "X-ray shows no signs of pneumonia. Mild bronchitis diagnosed.",
        doctor: "Dr. Michael Brown",
      },
      {
        id: "mh-7",
        date: "2024-08-15",
        type: "surgery",
        title: "Arthroscopic Knee Surgery",
        description: "Successful arthroscopic surgery to repair torn meniscus.",
        doctor: "Dr. James Wilson",
      },
    ],
    allergies: [],
    currentMedications: ["Ibuprofen 400mg as needed"],
    status: "active",
    assignedDoctor: "Dr. Michael Brown",
    department: "Pulmonology",
  },
  {
    id: "P-2024-004",
    firstName: "Lisa",
    lastName: "Anderson",
    dateOfBirth: "1995-02-14",
    gender: "female",
    email: "lisa.anderson@email.com",
    phone: "(555) 456-7890",
    address: "321 Elm Street, Somerville, MA 02143",
    bloodType: "AB+",
    emergencyContact: {
      name: "Mark Anderson",
      phone: "(555) 654-3210",
      relationship: "Father",
    },
    insuranceProvider: "Cigna",
    insuranceNumber: "CIG-987654321",
    medicalHistory: [
      {
        id: "mh-8",
        date: "2024-12-24",
        type: "surgery",
        title: "Appendectomy - Scheduled",
        description: "Emergency appendectomy scheduled. Patient showing signs of acute appendicitis.",
        doctor: "Dr. Patricia Miller",
      },
    ],
    allergies: ["Sulfa drugs", "Aspirin"],
    currentMedications: [],
    status: "active",
    admissionDate: "2024-12-24",
    assignedDoctor: "Dr. Patricia Miller",
    department: "Surgery",
  },
  {
    id: "P-2024-005",
    firstName: "James",
    lastName: "Wilson",
    dateOfBirth: "1965-09-30",
    gender: "male",
    email: "james.wilson@email.com",
    phone: "(555) 567-8901",
    address: "654 Cedar Lane, Brookline, MA 02445",
    bloodType: "O-",
    emergencyContact: {
      name: "Dorothy Wilson",
      phone: "(555) 543-2109",
      relationship: "Wife",
    },
    insuranceProvider: "Medicare",
    insuranceNumber: "MED-111222333",
    medicalHistory: [
      {
        id: "mh-9",
        date: "2024-12-22",
        type: "treatment",
        title: "Post-Surgery Recovery",
        description: "Discharged after successful cardiac bypass surgery. Follow-up in 2 weeks.",
        doctor: "Dr. Michael Brown",
      },
      {
        id: "mh-10",
        date: "2024-12-15",
        type: "surgery",
        title: "Coronary Artery Bypass",
        description: "Triple bypass surgery performed successfully.",
        doctor: "Dr. Robert Chen",
      },
    ],
    allergies: ["Codeine"],
    currentMedications: ["Aspirin 81mg", "Metoprolol 25mg", "Atorvastatin 40mg"],
    status: "discharged",
    admissionDate: "2024-12-14",
    dischargeDate: "2024-12-22",
    assignedDoctor: "Dr. Michael Brown",
    department: "Cardiology",
  },
  {
    id: "P-2024-006",
    firstName: "Emma",
    lastName: "Thompson",
    dateOfBirth: "1988-05-25",
    gender: "female",
    email: "emma.thompson@email.com",
    phone: "(555) 678-9012",
    address: "987 Birch Way, Newton, MA 02458",
    bloodType: "A-",
    emergencyContact: {
      name: "Michael Thompson",
      phone: "(555) 432-1098",
      relationship: "Husband",
    },
    insuranceProvider: "Harvard Pilgrim",
    insuranceNumber: "HP-444555666",
    medicalHistory: [
      {
        id: "mh-11",
        date: "2024-12-21",
        type: "diagnosis",
        title: "MRI Brain Scan",
        description: "MRI ordered due to recurring headaches. Results show no abnormalities.",
        doctor: "Dr. Sarah Johnson",
      },
      {
        id: "mh-12",
        date: "2024-10-05",
        type: "checkup",
        title: "Neurological Consultation",
        description: "Initial consultation for chronic migraine management.",
        doctor: "Dr. Sarah Johnson",
      },
    ],
    allergies: ["Ibuprofen"],
    currentMedications: ["Sumatriptan 50mg as needed", "Magnesium 400mg daily"],
    status: "active",
    assignedDoctor: "Dr. Sarah Johnson",
    department: "Neurology",
  },
  {
    id: "P-2024-007",
    firstName: "David",
    lastName: "Lee",
    dateOfBirth: "1972-12-03",
    gender: "male",
    email: "david.lee@email.com",
    phone: "(555) 789-0123",
    address: "246 Walnut Street, Medford, MA 02155",
    bloodType: "B-",
    emergencyContact: {
      name: "Susan Lee",
      phone: "(555) 321-0987",
      relationship: "Wife",
    },
    insuranceProvider: "Blue Cross Blue Shield",
    insuranceNumber: "BCBS-777888999",
    medicalHistory: [
      {
        id: "mh-13",
        date: "2024-12-20",
        type: "checkup",
        title: "Diabetes Management Review",
        description: "A1C levels improved to 6.8%. Continue current management plan.",
        doctor: "Dr. Sarah Johnson",
      },
      {
        id: "mh-14",
        date: "2024-03-15",
        type: "diagnosis",
        title: "Type 2 Diabetes Diagnosis",
        description: "Diagnosed with Type 2 diabetes. Started on Metformin.",
        doctor: "Dr. Sarah Johnson",
      },
    ],
    allergies: [],
    currentMedications: ["Metformin 1000mg twice daily", "Glipizide 5mg"],
    status: "active",
    assignedDoctor: "Dr. Sarah Johnson",
    department: "Endocrinology",
  },
  {
    id: "P-2024-008",
    firstName: "Sophia",
    lastName: "Martinez",
    dateOfBirth: "2000-08-18",
    gender: "female",
    email: "sophia.martinez@email.com",
    phone: "(555) 890-1234",
    address: "135 Spruce Court, Quincy, MA 02169",
    bloodType: "AB-",
    emergencyContact: {
      name: "Rosa Martinez",
      phone: "(555) 210-9876",
      relationship: "Mother",
    },
    insuranceProvider: "Tufts Health Plan",
    insuranceNumber: "THP-222333444",
    medicalHistory: [
      {
        id: "mh-15",
        date: "2024-12-19",
        type: "diagnosis",
        title: "Allergy Test Results",
        description: "Comprehensive allergy panel completed. Multiple environmental allergies identified.",
        doctor: "Dr. Emily Chen",
      },
    ],
    allergies: ["Pollen", "Dust mites", "Pet dander", "Mold"],
    currentMedications: ["Cetirizine 10mg daily", "Fluticasone nasal spray"],
    status: "active",
    assignedDoctor: "Dr. Emily Chen",
    department: "Allergy & Immunology",
  },
];

export const mockPatientStats = {
  total: 847,
  active: 623,
  discharged: 198,
  newThisMonth: 45,
};
