export const mockDocuments = [
  {
    id: "1",
    name: "Annual Physical Examination Report",
    category: "patient-records",
    size: "2.4 MB",
    uploadedAt: "2024-12-28",
    uploadedBy: "Dr. Sarah Johnson",
    patientId: "P-2024-001",
    patientName: "John Smith",
    status: "active",
    fileType: "PDF",
  },
  {
    id: "2",
    name: "Blood Work Analysis - Complete Panel",
    category: "lab-reports",
    size: "1.8 MB",
    uploadedAt: "2024-12-27",
    uploadedBy: "Lab Technician Mike",
    patientId: "P-2024-001",
    patientName: "John Smith",
    status: "active",
    fileType: "PDF",
  },
  {
    id: "3",
    name: "Antibiotic Prescription - Amoxicillin",
    category: "prescriptions",
    size: "245 KB",
    uploadedAt: "2024-12-26",
    uploadedBy: "Dr. Emily Chen",
    patientId: "P-2024-002",
    patientName: "Maria Garcia",
    status: "active",
    fileType: "PDF",
  },
  {
    id: "4",
    name: "Chest X-Ray Imaging Results",
    category: "imaging",
    size: "15.2 MB",
    uploadedAt: "2024-12-25",
    uploadedBy: "Radiology Dept.",
    patientId: "P-2024-003",
    patientName: "Robert Williams",
    status: "active",
    fileType: "DICOM",
  },
  {
    id: "5",
    name: "Surgery Consent Form - Appendectomy",
    category: "consent-forms",
    size: "890 KB",
    uploadedAt: "2024-12-24",
    uploadedBy: "Nurse Patricia",
    patientId: "P-2024-004",
    patientName: "Lisa Anderson",
    status: "pending",
    fileType: "PDF",
  },
  {
    id: "6",
    name: "Insurance Claim Form - Blue Cross",
    category: "insurance",
    size: "1.1 MB",
    uploadedAt: "2024-12-23",
    uploadedBy: "Billing Dept.",
    patientId: "P-2024-002",
    patientName: "Maria Garcia",
    status: "active",
    fileType: "PDF",
  },
  {
    id: "7",
    name: "Hospital Discharge Summary",
    category: "discharge-summary",
    size: "3.2 MB",
    uploadedAt: "2024-12-22",
    uploadedBy: "Dr. Michael Brown",
    patientId: "P-2024-005",
    patientName: "James Wilson",
    status: "archived",
    fileType: "PDF",
  },
  {
    id: "8",
    name: "MRI Scan - Brain Imaging",
    category: "imaging",
    size: "28.5 MB",
    uploadedAt: "2024-12-21",
    uploadedBy: "Radiology Dept.",
    patientId: "P-2024-006",
    patientName: "Emma Thompson",
    status: "active",
    fileType: "DICOM",
  },
  {
    id: "9",
    name: "Diabetes Management Plan",
    category: "patient-records",
    size: "1.5 MB",
    uploadedAt: "2024-12-20",
    uploadedBy: "Dr. Sarah Johnson",
    patientId: "P-2024-007",
    patientName: "David Lee",
    status: "active",
    fileType: "PDF",
  },
  {
    id: "10",
    name: "Allergy Test Results",
    category: "lab-reports",
    size: "2.1 MB",
    uploadedAt: "2024-12-19",
    uploadedBy: "Lab Technician Sarah",
    patientId: "P-2024-008",
    patientName: "Sophia Martinez",
    status: "active",
    fileType: "PDF",
  },
];

export const mockStats = {
  total: 1247,
  thisMonth: 156,
  pending: 23,
  archived: 89,
};
