import { Notification } from '@/types/notification';

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'urgent',
    category: 'emergency',
    title: 'Critical Patient Alert',
    message: 'Patient John Smith in Room 302 requires immediate attention. Vital signs deteriorating.',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    isRead: false,
    patientName: 'John Smith',
    roomNumber: '302',
  },
  {
    id: '2',
    type: 'urgent',
    category: 'emergency',
    title: 'Code Blue - ICU',
    message: 'Code Blue activated in ICU Room 105. Emergency response team dispatched.',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    isRead: false,
    roomNumber: '105',
  },
  {
    id: '3',
    type: 'warning',
    category: 'lab',
    title: 'Abnormal Lab Results',
    message: 'Patient Maria Garcia has elevated troponin levels. Review recommended.',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    isRead: false,
    patientName: 'Maria Garcia',
  },
  {
    id: '4',
    type: 'warning',
    category: 'pharmacy',
    title: 'Medication Interaction Alert',
    message: 'Potential drug interaction detected for patient Robert Chen. Please verify prescription.',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    isRead: false,
    patientName: 'Robert Chen',
  },
  {
    id: '5',
    type: 'info',
    category: 'appointment',
    title: 'Upcoming Surgery',
    message: 'Scheduled appendectomy for patient Emily Davis at 2:00 PM in OR-3.',
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    isRead: true,
    patientName: 'Emily Davis',
  },
  {
    id: '6',
    type: 'success',
    category: 'patient',
    title: 'Patient Discharged',
    message: 'Patient Michael Brown has been successfully discharged from Room 215.',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    isRead: true,
    patientName: 'Michael Brown',
    roomNumber: '215',
  },
  {
    id: '7',
    type: 'info',
    category: 'lab',
    title: 'Lab Results Ready',
    message: 'Complete blood count results are now available for patient Sarah Wilson.',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    isRead: true,
    patientName: 'Sarah Wilson',
  },
  {
    id: '8',
    type: 'warning',
    category: 'patient',
    title: 'Patient Fall Risk',
    message: 'Patient David Lee has been flagged as high fall risk. Extra precautions advised.',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    isRead: false,
    patientName: 'David Lee',
    roomNumber: '418',
  },
  {
    id: '9',
    type: 'success',
    category: 'appointment',
    title: 'Appointment Confirmed',
    message: 'Follow-up appointment confirmed for patient Lisa Anderson on Friday at 10:00 AM.',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    isRead: true,
    patientName: 'Lisa Anderson',
  },
  {
    id: '10',
    type: 'info',
    category: 'system',
    title: 'System Maintenance',
    message: 'Scheduled maintenance tonight from 2:00 AM to 4:00 AM. Some services may be unavailable.',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    isRead: true,
  },
];
