import { subDays, addDays } from 'date-fns';

const today = new Date();

export const mockPrescriptions = [
  {
    id: 'rx-001',
    patientId: 'p-001',
    patientName: 'Rahul Sharma',
    patientMrn: 'MRN-2024-001',
    doctor: 'Dr. Priya Patel',
    diagnosis: 'Upper Respiratory Infection',
    prescribedDate: subDays(today, 2),
    status: 'active',
    refillsRemaining: 2,
    notes: 'Patient allergic to penicillin. Monitor for side effects.',
    tags: ['tag8', 'tag2'],
    categories: ['cat1'],
    medicines: [
      {
        name: 'Azithromycin',
        dosage: '500mg',
        frequency: 'once-daily',
        duration: '5-days',
        route: 'oral',
        instructions: 'Take with food',
        quantity: 5,
      },
      {
        name: 'Cetirizine',
        dosage: '10mg',
        frequency: 'once-daily',
        duration: '7-days',
        route: 'oral',
        instructions: 'Take at bedtime',
        quantity: 7,
      },
    ],
  },
  {
    id: 'rx-002',
    patientId: 'p-002',
    patientName: 'Amit Kumar',
    patientMrn: 'MRN-2024-002',
    doctor: 'Dr. Rajesh Gupta',
    diagnosis: 'Type 2 Diabetes - Routine Management',
    prescribedDate: subDays(today, 30),
    status: 'active',
    refillsRemaining: 5,
    notes: 'Continue current regimen. Check HbA1c in 3 months.',
    tags: ['tag10'],
    categories: ['cat3'],
    medicines: [
      {
        name: 'Metformin',
        dosage: '1000mg',
        frequency: 'twice-daily',
        duration: '90-days',
        route: 'oral',
        instructions: 'Take with meals',
        quantity: 180,
      },
      {
        name: 'Lisinopril',
        dosage: '10mg',
        frequency: 'once-daily',
        duration: '90-days',
        route: 'oral',
        instructions: 'Take in the morning',
        quantity: 90,
      },
    ],
  },
  {
    id: 'rx-003',
    patientId: 'p-003',
    patientName: 'Sneha Verma',
    patientMrn: 'MRN-2024-003',
    doctor: 'Dr. Sunita Rao',
    diagnosis: 'Hypertension',
    prescribedDate: subDays(today, 60),
    status: 'active',
    refillsRemaining: 3,
    notes: 'Blood pressure well controlled. Continue current dose.',
    tags: [],
    categories: ['cat3', 'cat5'],
    medicines: [
      {
        name: 'Amlodipine',
        dosage: '5mg',
        frequency: 'once-daily',
        duration: '30-days',
        route: 'oral',
        instructions: 'Take in the evening',
        quantity: 30,
      },
    ],
  },
  {
    id: 'rx-004',
    patientId: 'p-004',
    patientName: 'Vikram Reddy',
    patientMrn: 'MRN-2024-004',
    doctor: 'Dr. Priya Patel',
    diagnosis: 'Acute Bronchitis',
    prescribedDate: subDays(today, 14),
    status: 'completed',
    refillsRemaining: 0,
    notes: 'Patient recovered. No follow-up needed.',
    tags: [],
    categories: ['cat1'],
    medicines: [
      {
        name: 'Amoxicillin',
        dosage: '500mg',
        frequency: 'thrice-daily',
        duration: '10-days',
        route: 'oral',
        instructions: 'Complete full course',
        quantity: 30,
      },
      {
        name: 'Albuterol',
        dosage: '90mcg',
        frequency: 'as-needed',
        duration: '14-days',
        route: 'inhalation',
        instructions: '2 puffs every 4-6 hours as needed',
        quantity: 1,
      },
    ],
  },
  {
    id: 'rx-005',
    patientId: 'p-005',
    patientName: 'Kavita Nair',
    patientMrn: 'MRN-2024-005',
    doctor: 'Dr. Rajesh Gupta',
    diagnosis: 'Migraine',
    prescribedDate: subDays(today, 7),
    status: 'active',
    refillsRemaining: 4,
    notes: 'For acute migraine attacks. Limit to 10 days per month.',
    tags: ['tag2'],
    categories: [],
    medicines: [
      {
        name: 'Sumatriptan',
        dosage: '50mg',
        frequency: 'as-needed',
        duration: '30-days',
        route: 'oral',
        instructions: 'Take at onset of migraine. May repeat after 2 hours.',
        quantity: 9,
      },
    ],
  },
  {
    id: 'rx-006',
    patientId: 'p-001',
    patientName: 'Rahul Sharma',
    patientMrn: 'MRN-2024-001',
    doctor: 'Dr. Sunita Rao',
    diagnosis: 'Anxiety Disorder',
    prescribedDate: subDays(today, 45),
    status: 'on-hold',
    refillsRemaining: 2,
    notes: 'On hold pending psychiatric evaluation.',
    tags: ['tag7'],
    categories: [],
    medicines: [
      {
        name: 'Sertraline',
        dosage: '50mg',
        frequency: 'once-daily',
        duration: 'ongoing',
        route: 'oral',
        instructions: 'Take in the morning with food',
        quantity: 30,
      },
    ],
  },
  {
    id: 'rx-007',
    patientId: 'p-006',
    patientName: 'Arun Joshi',
    patientMrn: 'MRN-2024-006',
    doctor: 'Dr. Priya Patel',
    diagnosis: 'Chronic Pain - Lower Back',
    prescribedDate: subDays(today, 5),
    status: 'discontinued',
    refillsRemaining: 0,
    notes: 'Discontinued due to side effects. Switch to alternative.',
    tags: ['tag7'],
    categories: [],
    medicines: [
      {
        name: 'Tramadol',
        dosage: '50mg',
        frequency: 'every-6-hours',
        duration: '14-days',
        route: 'oral',
        instructions: 'Take as needed for pain',
        quantity: 56,
      },
    ],
  },
  {
    id: 'rx-008',
    patientId: 'p-002',
    patientName: 'Amit Kumar',
    patientMrn: 'MRN-2024-002',
    doctor: 'Dr. Rajesh Gupta',
    diagnosis: 'Hyperlipidemia',
    prescribedDate: subDays(today, 90),
    status: 'active',
    refillsRemaining: 2,
    notes: 'LDL target <100. Recheck lipid panel in 6 weeks.',
    tags: ['tag10'],
    categories: ['cat3', 'cat5'],
    medicines: [
      {
        name: 'Atorvastatin',
        dosage: '20mg',
        frequency: 'at-bedtime',
        duration: '90-days',
        route: 'oral',
        instructions: 'Take at bedtime',
        quantity: 90,
      },
    ],
  },
];

// Mock doctors for selection (Indian names)
export const mockDoctors = [
  { id: 'd-001', name: 'Dr. Priya Patel', specialty: 'Family Medicine' },
  { id: 'd-002', name: 'Dr. Rajesh Gupta', specialty: 'Internal Medicine' },
  { id: 'd-003', name: 'Dr. Sunita Rao', specialty: 'Cardiology' },
  { id: 'd-004', name: 'Dr. Anand Sharma', specialty: 'Neurology' },
  { id: 'd-005', name: 'Dr. Meera Nair', specialty: 'Pulmonology' },
];

// Mock patients for selection (Indian names)
export const mockPatientsList = [
  { id: 'p-001', name: 'Rahul Sharma', mrn: 'MRN-2024-001' },
  { id: 'p-002', name: 'Amit Kumar', mrn: 'MRN-2024-002' },
  { id: 'p-003', name: 'Sneha Verma', mrn: 'MRN-2024-003' },
  { id: 'p-004', name: 'Vikram Reddy', mrn: 'MRN-2024-004' },
  { id: 'p-005', name: 'Kavita Nair', mrn: 'MRN-2024-005' },
  { id: 'p-006', name: 'Arun Joshi', mrn: 'MRN-2024-006' },
];
