export const categories = [
  { value: "all", label: "All Products" },
  { value: "crystals", label: "Crystals" },
  { value: "jewelry", label: "Jewelry" },
  { value: "meditation", label: "Meditation" },
  { value: "vastu", label: "Vastu" },
];

export const products = [
  {
    id: "crystal-bracelets",
    image: "/crystalaura/crystal-bracelet.jpg",
    title: "Crystal Bracelets",
    description: "Handcrafted with amethyst, rose quartz & healing stones",
    longDescription: "Our crystal bracelets are lovingly handcrafted using genuine amethyst, rose quartz, tiger's eye, and other powerful healing stones. Each bracelet is strung on durable elastic cord and energetically cleansed before shipping. Perfect for daily wear and continuous energy alignment.",
    price: "From ₹499",
    priceNum: 499,
    category: "jewelry",
  },
  {
    id: "healing-spheres",
    image: "/crystalaura/healing-sphere.jpg",
    title: "Healing Spheres",
    description: "Clear quartz & crystal spheres for meditation",
    longDescription: "Our crystal spheres are polished from natural clear quartz and other premium stones. Each sphere radiates energy uniformly in all directions, making them ideal for meditation, scrying, and room energy harmonization. Available in multiple sizes from 30mm to 100mm.",
    price: "From ₹1,299",
    priceNum: 1299,
    category: "meditation",
  },
  {
    id: "spiritual-pyramids",
    image: "/crystalaura/spiritual-pyramid.jpg",
    title: "Spiritual Pyramids",
    description: "Orgonite pyramids charged with positive energy",
    longDescription: "Our orgonite pyramids are handcrafted with a blend of metal shavings, resin, and genuine crystals. They convert negative energy into positive life force, enhance meditation, and are perfect for Vastu correction. Each pyramid is unique and charged under moonlight.",
    price: "From ₹899",
    priceNum: 899,
    category: "vastu",
  },
  {
    id: "energy-stones",
    image: "/crystalaura/energy-stones.jpg",
    title: "Energy Stones",
    description: "Tumbled & polished stones for chakra healing",
    longDescription: "Our tumbled and polished energy stones are sourced from mines across India, Brazil, and Madagascar. Each stone is carefully selected for its clarity, color, and energetic properties. Use them for chakra healing, crystal grids, or carry them in your pocket for daily protection.",
    price: "From ₹199",
    priceNum: 199,
    category: "crystals",
  },
  {
    id: "mala-prayer-beads",
    image: "/crystalaura/mala-beads.jpg",
    title: "Mala Prayer Beads",
    description: "Rudraksha & crystal mala for japa meditation",
    longDescription: "Traditional 108-bead mala necklaces crafted from genuine Rudraksha seeds and healing crystals. Perfect for japa meditation, mantra counting, and spiritual practice. Each mala is hand-knotted between beads and features a guru bead for easy counting.",
    price: "From ₹699",
    priceNum: 699,
    category: "jewelry",
  },
  {
    id: "crystal-pendulums",
    image: "/crystalaura/crystal-pendulum.jpg",
    title: "Crystal Pendulums",
    description: "Amethyst & quartz pendulums for divination",
    longDescription: "Our crystal pendulums are precision-crafted from natural amethyst, clear quartz, and other gemstones. They are balanced for smooth swinging and come with a silver-plated chain. Ideal for dowsing, divination, chakra balancing, and energy healing work.",
    price: "From ₹349",
    priceNum: 349,
    category: "crystals",
  },
  {
    id: "amethyst-geodes",
    image: "/crystalaura/crystal-geode.jpg",
    title: "Amethyst Geodes",
    description: "Natural geode bookends & display pieces",
    longDescription: "Stunning natural amethyst geodes sourced from Uruguay and Brazil. Each geode is unique with deep purple crystals formed over millions of years. Available as bookends, cathedral pieces, and tabletop displays. They bring calming energy and are perfect for home or office décor.",
    price: "From ₹2,499",
    priceNum: 2499,
    category: "crystals",
  },
  {
    id: "chakra-stone-sets",
    image: "/crystalaura/chakra-set.jpg",
    title: "Chakra Stone Sets",
    description: "7 chakra healing stones for energy alignment",
    longDescription: "Complete set of 7 genuine chakra stones — Red Jasper, Carnelian, Citrine, Green Aventurine, Lapis Lazuli, Amethyst, and Clear Quartz. Each set comes in a velvet pouch with a chakra guide card. Perfect for energy healing, meditation, and Reiki practice.",
    price: "From ₹599",
    priceNum: 599,
    category: "crystals",
  },
  {
    id: "himalayan-salt-lamps",
    image: "/crystalaura/salt-lamp.jpg",
    title: "Himalayan Salt Lamps",
    description: "Natural salt lamps for air purification & calm",
    longDescription: "Hand-carved from pure Himalayan pink salt crystals, our salt lamps emit a warm, soothing amber glow. They naturally ionize the air, reduce allergens, and create a calming atmosphere. Each lamp comes with a dimmer switch and wooden base. Available in 2kg to 10kg sizes.",
    price: "From ₹799",
    priceNum: 799,
    category: "vastu",
  },
  {
    id: "selenite-wands",
    image: "/crystalaura/crystal-wand.jpg",
    title: "Selenite Wands",
    description: "Energy cleansing wands for aura healing",
    longDescription: "Our selenite wands are polished from natural selenite crystal, known for its powerful cleansing and charging properties. Use them to cleanse your aura, charge other crystals, or direct healing energy during meditation. Available in 6-inch and 10-inch lengths.",
    price: "From ₹449",
    priceNum: 449,
    category: "crystals",
  },
  {
    id: "crystal-trees",
    image: "/crystalaura/crystal-tree.jpg",
    title: "Crystal Trees",
    description: "Gemstone bonsai trees for prosperity & Vastu",
    longDescription: "Beautiful handcrafted gemstone bonsai trees featuring genuine crystal chips wired onto a metal trunk. Available in amethyst, citrine, rose quartz, and multi-stone varieties. They attract prosperity, positive energy, and are excellent Vastu remedies for wealth corners.",
    price: "From ₹1,199",
    priceNum: 1199,
    category: "vastu",
  },
  {
    id: "sage-palo-santo",
    image: "/crystalaura/sage-smudge.jpg",
    title: "Sage & Palo Santo",
    description: "Smudge kits for space cleansing & purification",
    longDescription: "Premium white sage bundles and Palo Santo sticks sourced sustainably. Our smudge kits include everything you need for space cleansing — sage bundle, Palo Santo sticks, an abalone shell, and a feather. Perfect for clearing negative energy from your home or workspace.",
    price: "From ₹299",
    priceNum: 299,
    category: "meditation",
  },
];
