import { subDays, subYears } from 'date-fns';

const today = new Date();

export const mockPatients = [
  {
    id: 'p1',
    mrn: 'MRN-2024-0001',
    firstName: 'Rahul',
    lastName: 'Sharma',
    fullName: 'Rahul Sharma',
    email: 'rahul.sharma@email.com',
    phone: '+91 98765 43210',
    dateOfBirth: subYears(today, 45),
    age: 45,
    gender: 'male',
    bloodGroup: 'b+',
    status: 'active',
    address: '123 MG Road, Bangalore, Karnataka 560001',
    emergencyContact: {
      name: 'Priya Sharma',
      phone: '+91 98765 43211',
      relationship: 'spouse',
    },
    insurance: {
      provider: 'star',
      policyNumber: 'STR-2024-789456',
      validUntil: new Date(2025, 11, 31),
    },
    allergies: [
      { name: 'Penicillin', severity: 'severe', notes: 'Causes anaphylaxis' },
      { name: 'Peanuts', severity: 'moderate', notes: 'Skin rash' },
    ],
    vitals: [
      { type: 'blood_pressure', value: '120/80', recordedAt: subDays(today, 1) },
      { type: 'heart_rate', value: '72', recordedAt: subDays(today, 1) },
      { type: 'temperature', value: '98.6', recordedAt: subDays(today, 1) },
      { type: 'oxygen_saturation', value: '98', recordedAt: subDays(today, 1) },
      { type: 'weight', value: '75', recordedAt: subDays(today, 7) },
      { type: 'height', value: '175', recordedAt: subDays(today, 30) },
    ],
    medicalHistory: [
      { condition: 'Hypertension', diagnosedDate: subYears(today, 5), status: 'ongoing', notes: 'Controlled with medication' },
      { condition: 'Type 2 Diabetes', diagnosedDate: subYears(today, 3), status: 'ongoing', notes: 'Diet controlled' },
    ],
    prescriptions: [
      {
        id: 'rx1',
        date: subDays(today, 7),
        doctor: 'Dr. Priya Patel',
        medicines: [
          { name: 'Amlodipine', dosage: '5mg', frequency: 'Once daily', duration: '30 days' },
          { name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: '30 days' },
        ],
      },
    ],
    documents: [
      { id: 'doc1', name: 'Blood Test Report', type: 'Lab Report', date: subDays(today, 7), url: '#' },
      { id: 'doc2', name: 'ECG Report', type: 'Diagnostic', date: subDays(today, 14), url: '#' },
    ],
    registeredAt: subDays(today, 365),
    lastVisit: subDays(today, 7),
    // Taxonomy fields
    tags: ['tag8', 'tag10'],
    categories: ['cat3', 'cat5'],
  },
  {
    id: 'p2',
    mrn: 'MRN-2024-0002',
    firstName: 'Sneha',
    lastName: 'Gupta',
    fullName: 'Sneha Gupta',
    email: 'sneha.gupta@email.com',
    phone: '+91 98765 43212',
    dateOfBirth: subYears(today, 32),
    age: 32,
    gender: 'female',
    bloodGroup: 'o+',
    status: 'active',
    address: '456 Park Street, Kolkata, West Bengal 700016',
    emergencyContact: {
      name: 'Amit Gupta',
      phone: '+91 98765 43213',
      relationship: 'spouse',
    },
    insurance: {
      provider: 'hdfc',
      policyNumber: 'HDFC-2024-123456',
      validUntil: new Date(2025, 6, 30),
    },
    allergies: [],
    vitals: [
      { type: 'blood_pressure', value: '118/76', recordedAt: subDays(today, 3) },
      { type: 'heart_rate', value: '68', recordedAt: subDays(today, 3) },
      { type: 'temperature', value: '98.4', recordedAt: subDays(today, 3) },
      { type: 'oxygen_saturation', value: '99', recordedAt: subDays(today, 3) },
    ],
    medicalHistory: [],
    prescriptions: [],
    documents: [],
    registeredAt: subDays(today, 180),
    lastVisit: subDays(today, 3),
    tags: ['tag5'],
    categories: ['cat1'],
  },
  {
    id: 'p3',
    mrn: 'MRN-2024-0003',
    firstName: 'Amit',
    lastName: 'Patel',
    fullName: 'Amit Patel',
    email: 'amit.patel@email.com',
    phone: '+91 98765 43214',
    dateOfBirth: subYears(today, 28),
    age: 28,
    gender: 'male',
    bloodGroup: 'a+',
    status: 'admitted',
    address: '789 Anna Nagar, Chennai, Tamil Nadu 600040',
    emergencyContact: {
      name: 'Meera Patel',
      phone: '+91 98765 43215',
      relationship: 'parent',
    },
    insurance: {
      provider: 'icici',
      policyNumber: 'ICICI-2024-456789',
      validUntil: new Date(2025, 9, 15),
    },
    allergies: [
      { name: 'Aspirin', severity: 'mild', notes: 'Stomach upset' },
    ],
    vitals: [
      { type: 'blood_pressure', value: '135/90', recordedAt: today },
      { type: 'heart_rate', value: '88', recordedAt: today },
      { type: 'temperature', value: '100.2', recordedAt: today },
      { type: 'oxygen_saturation', value: '96', recordedAt: today },
    ],
    medicalHistory: [
      { condition: 'Knee Surgery', diagnosedDate: subDays(today, 2), status: 'recovering', notes: 'Post-operative care' },
    ],
    prescriptions: [
      {
        id: 'rx2',
        date: today,
        doctor: 'Dr. Amit Sharma',
        medicines: [
          { name: 'Paracetamol', dosage: '650mg', frequency: 'Every 6 hours', duration: '5 days' },
          { name: 'Antibiotics', dosage: '500mg', frequency: 'Twice daily', duration: '7 days' },
        ],
      },
    ],
    documents: [],
    registeredAt: subDays(today, 90),
    lastVisit: today,
    tags: ['tag1', 'tag2'],
    categories: ['cat2'],
  },
  {
    id: 'p4',
    mrn: 'MRN-2024-0004',
    firstName: 'Priya',
    lastName: 'Verma',
    fullName: 'Priya Verma',
    email: 'priya.verma@email.com',
    phone: '+91 98765 43216',
    dateOfBirth: subYears(today, 55),
    age: 55,
    gender: 'female',
    bloodGroup: 'ab+',
    status: 'critical',
    address: '321 Civil Lines, Delhi 110054',
    emergencyContact: {
      name: 'Raj Verma',
      phone: '+91 98765 43217',
      relationship: 'child',
    },
    insurance: {
      provider: 'max',
      policyNumber: 'MAX-2024-789012',
      validUntil: new Date(2025, 3, 20),
    },
    allergies: [
      { name: 'Sulfa drugs', severity: 'severe', notes: 'Severe allergic reaction' },
      { name: 'Latex', severity: 'moderate', notes: 'Skin irritation' },
    ],
    vitals: [
      { type: 'blood_pressure', value: '160/100', recordedAt: today },
      { type: 'heart_rate', value: '95', recordedAt: today },
      { type: 'temperature', value: '101.5', recordedAt: today },
      { type: 'oxygen_saturation', value: '92', recordedAt: today },
    ],
    medicalHistory: [
      { condition: 'Cardiac Arrhythmia', diagnosedDate: subYears(today, 2), status: 'ongoing', notes: 'Requires monitoring' },
      { condition: 'Pneumonia', diagnosedDate: subDays(today, 5), status: 'active', notes: 'Currently being treated' },
    ],
    prescriptions: [],
    documents: [],
    registeredAt: subDays(today, 500),
    lastVisit: today,
    tags: ['tag1', 'tag3', 'tag8'],
    categories: ['cat2', 'cat5'],
  },
  {
    id: 'p5',
    mrn: 'MRN-2024-0005',
    firstName: 'Vikram',
    lastName: 'Mehta',
    fullName: 'Vikram Mehta',
    email: 'vikram.mehta@email.com',
    phone: '+91 98765 43218',
    dateOfBirth: subYears(today, 62),
    age: 62,
    gender: 'male',
    bloodGroup: 'o-',
    status: 'discharged',
    address: '567 Juhu, Mumbai, Maharashtra 400049',
    emergencyContact: {
      name: 'Anita Mehta',
      phone: '+91 98765 43219',
      relationship: 'spouse',
    },
    insurance: {
      provider: 'bajaj',
      policyNumber: 'BAJ-2024-345678',
      validUntil: new Date(2025, 8, 10),
    },
    allergies: [],
    vitals: [
      { type: 'blood_pressure', value: '128/82', recordedAt: subDays(today, 2) },
      { type: 'heart_rate', value: '76', recordedAt: subDays(today, 2) },
    ],
    medicalHistory: [
      { condition: 'Hip Replacement', diagnosedDate: subDays(today, 14), status: 'recovered', notes: 'Successful surgery' },
    ],
    prescriptions: [],
    documents: [],
    registeredAt: subDays(today, 400),
    lastVisit: subDays(today, 2),
    tags: ['tag2', 'tag10'],
    categories: ['cat1'],
  },
  {
    id: 'p6',
    mrn: 'MRN-2024-0006',
    firstName: 'Anjali',
    lastName: 'Reddy',
    fullName: 'Anjali Reddy',
    email: 'anjali.reddy@email.com',
    phone: '+91 98765 43220',
    dateOfBirth: subYears(today, 38),
    age: 38,
    gender: 'female',
    bloodGroup: 'b-',
    status: 'active',
    address: '890 Banjara Hills, Hyderabad, Telangana 500034',
    emergencyContact: {
      name: 'Krishna Reddy',
      phone: '+91 98765 43221',
      relationship: 'sibling',
    },
    insurance: {
      provider: 'none',
      policyNumber: '',
      validUntil: null,
    },
    allergies: [
      { name: 'Shellfish', severity: 'severe', notes: 'Anaphylactic reaction' },
    ],
    vitals: [
      { type: 'blood_pressure', value: '115/75', recordedAt: subDays(today, 10) },
      { type: 'heart_rate', value: '70', recordedAt: subDays(today, 10) },
    ],
    medicalHistory: [],
    prescriptions: [],
    documents: [],
    registeredAt: subDays(today, 60),
    lastVisit: subDays(today, 10),
    tags: ['tag4', 'tag8'],
    categories: [],
  },
];
