export const TaskType = {
    LAUNCH_BROWSER: 'LAUNCH_BROWSER',
    PAGE_TO_HTML: 'PAGE_TO_HTML',
    EXTRACT_TEXT_FROM_ELEMENT: 'EXTRACT_TEXT_FROM_ELEMENT',
    EXTRACT_DATA_WITH_AI: 'EXTRACT_DATA_WITH_AI',
    DELIVER_VIA_WEBHOOK: 'DELIVER_VIA_WEBHOOK',
    CLICK_ELEMENT: 'CLICK_ELEMENT',
    FILL_INPUT: 'FILL_INPUT',
    WAIT_FOR_ELEMENT: 'WAIT_FOR_ELEMENT',
    READ_PROPERTY_FROM_JSON: 'READ_PROPERTY_FROM_JSON',
};

export const TaskParamTypes = {
    STRING: 'STRING',
    BROWSER_INSTANCE: 'BROWSER_INSTANCE',
    SELECT: 'SELECT',
    CREDENTIAL: 'CREDENTIAL',
};

export const AppNodeData = {
    type: 'Node',
    inputs: {},
    outputs: {},
    invalid: false,
};
