export const credentialsTypes = [
    {
        id: 'all',
        type: 'all',
        platform: 'all',
        name: 'All Credentials',
        icon: 'settings-2',
        description: 'All Credentials',
        model: null,
        provider: null,
    },
    {
        id: 'llm',
        type: 'llm',
        platform: 'llm',
        name: 'AI Models',
        icon: 'brain',
        description: 'Large Language Models',
        model: null,
        provider: null,
    },
    {
        id: 'social',
        type: 'social',
        platform: 'social',
        name: 'Social',
        icon: 'scan-face',
        description: 'Social Media Accounts',
        model: null,
        provider: null,
    },
    {
        id: 'cloud',
        type: 'cloud',
        platform: 'cloud',
        name: 'Cloud',
        icon: 'cloud',
        description: 'Cloud Services',
        model: null,
        provider: null,
    },
    {
        id: 'other',
        type: 'other',
        platform: 'other',
        name: 'Other',
        icon: 'settings-2',
        description: 'Other Credentials',
        model: null,
        provider: null,
    }
];
