const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const gitHooksDir = path.join(rootDir, '.git', 'hooks');

/**
 * Gets the current Git branch name.
 */
function getCurrentBranch() {
    try {
        return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
    } catch (error) {
        console.error('Error fetching git branch:', error.message);
        return null;
    }
}

/**
 * Switches the .env.local file based on the current branch.
 */
function switchEnv() {
    const branch = getCurrentBranch();
    if (!branch) return;

    const branchEnvFile = path.join(rootDir, `.env.${branch}`);
    const targetEnvFile = path.join(rootDir, '.env.local');

    if (fs.existsSync(branchEnvFile)) {
        console.log(`\n🔄 Branch-Specific Env: Found .env.${branch}`);
        try {
            fs.copyFileSync(branchEnvFile, targetEnvFile);
            console.log(`✅ Successfully updated .env.local from .env.${branch}\n`);
        } catch (error) {
            console.error(`❌ Failed to copy .env.${branch} to .env.local:`, error.message);
        }
    } else {
        console.log(`\nℹ️  Branch-Specific Env: No specific file found for branch "${branch}" (.env.${branch} missing).`);
        console.log(`   Leaving .env.local as is.\n`);
    }
}

/**
 * Installs the Git post-checkout hook.
 */
function installHook() {
    const hookPath = path.join(gitHooksDir, 'post-checkout');
    const hookContent = `#!/bin/sh
# This hook was automatically generated by manage-env.js
node scripts/manage-env.js --switch
`;

    if (!fs.existsSync(gitHooksDir)) {
        console.error('❌ .git/hooks directory not found. Are you in a Git repository?');
        return;
    }

    try {
        fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });
        console.log('✅ Git post-checkout hook installed successfully.');
    } catch (error) {
        console.error('❌ Failed to install Git hook:', error.message);
    }
}

// Command line arguments handling
const args = process.argv.slice(2);

if (args.includes('--install')) {
    installHook();
} else if (args.includes('--switch')) {
    switchEnv();
} else {
    // Default to switching if no args provided
    switchEnv();
}
