import { addDays, subDays } from 'date-fns';

export const mockInventoryItems = [
  {
    id: 'inv_001',
    sku: 'MED-GLV-001',
    name: 'Surgical Gloves (Latex)',
    description: 'Sterile latex surgical gloves, powder-free',
    category: 'medical_supplies',
    unit: 'box',
    quantity: 150,
    reorderLevel: 50,
    costPrice: 450,
    sellingPrice: 550,
    location: 'main_store',
    supplier: 'sup_001',
    batchNumber: 'BATCH-2024-001',
    expiryDate: addDays(new Date(), 365),
    lastRestocked: subDays(new Date(), 15),
    notes: 'Size: Medium',
    isActive: true,
  },
  {
    id: 'inv_002',
    sku: 'EQP-MON-001',
    name: 'Blood Pressure Monitor',
    description: 'Digital automatic blood pressure monitor with memory function',
    category: 'equipment',
    unit: 'piece',
    quantity: 25,
    reorderLevel: 10,
    costPrice: 2500,
    sellingPrice: 3200,
    location: 'main_store',
    supplier: 'sup_002',
    batchNumber: null,
    expiryDate: null,
    lastRestocked: subDays(new Date(), 30),
    notes: 'Warranty: 2 years',
    isActive: true,
  },
  {
    id: 'inv_003',
    sku: 'CON-SYR-001',
    name: 'Disposable Syringes 5ml',
    description: 'Single-use sterile syringes with needle',
    category: 'consumables',
    unit: 'box',
    quantity: 8,
    reorderLevel: 20,
    costPrice: 180,
    sellingPrice: 250,
    location: 'pharmacy_store',
    supplier: 'sup_001',
    batchNumber: 'BATCH-2024-015',
    expiryDate: addDays(new Date(), 180),
    lastRestocked: subDays(new Date(), 45),
    notes: '100 pcs per box',
    isActive: true,
  },
  {
    id: 'inv_004',
    sku: 'LAB-TUB-001',
    name: 'Blood Collection Tubes (EDTA)',
    description: 'Vacuum blood collection tubes with EDTA anticoagulant',
    category: 'laboratory',
    unit: 'pack',
    quantity: 45,
    reorderLevel: 30,
    costPrice: 850,
    sellingPrice: 1100,
    location: 'lab_store',
    supplier: 'sup_004',
    batchNumber: 'BATCH-2024-022',
    expiryDate: addDays(new Date(), 25),
    lastRestocked: subDays(new Date(), 60),
    notes: '50 tubes per pack',
    isActive: true,
  },
  {
    id: 'inv_005',
    sku: 'SUR-SCA-001',
    name: 'Surgical Scalpel Blades',
    description: 'Stainless steel surgical scalpel blades, sterile',
    category: 'surgical',
    unit: 'box',
    quantity: 35,
    reorderLevel: 15,
    costPrice: 650,
    sellingPrice: 850,
    location: 'ot_store',
    supplier: 'sup_003',
    batchNumber: 'BATCH-2024-008',
    expiryDate: addDays(new Date(), 730),
    lastRestocked: subDays(new Date(), 20),
    notes: 'Size: #10, 100 pcs per box',
    isActive: true,
  },
  {
    id: 'inv_006',
    sku: 'PPE-MSK-001',
    name: 'N95 Respirator Masks',
    description: 'NIOSH approved N95 respiratory masks',
    category: 'ppe',
    unit: 'box',
    quantity: 0,
    reorderLevel: 25,
    costPrice: 1200,
    sellingPrice: 1500,
    location: 'main_store',
    supplier: 'sup_005',
    batchNumber: 'BATCH-2024-030',
    expiryDate: addDays(new Date(), 545),
    lastRestocked: subDays(new Date(), 90),
    notes: '20 masks per box',
    isActive: true,
  },
  {
    id: 'inv_007',
    sku: 'CON-BAN-001',
    name: 'Adhesive Bandages (Assorted)',
    description: 'Sterile adhesive bandages in various sizes',
    category: 'consumables',
    unit: 'box',
    quantity: 120,
    reorderLevel: 40,
    costPrice: 220,
    sellingPrice: 320,
    location: 'emergency_store',
    supplier: 'sup_001',
    batchNumber: 'BATCH-2024-012',
    expiryDate: addDays(new Date(), 900),
    lastRestocked: subDays(new Date(), 10),
    notes: '100 pcs per box',
    isActive: true,
  },
  {
    id: 'inv_008',
    sku: 'EQP-THM-001',
    name: 'Digital Thermometer',
    description: 'Infrared non-contact digital thermometer',
    category: 'equipment',
    unit: 'piece',
    quantity: 18,
    reorderLevel: 10,
    costPrice: 1800,
    sellingPrice: 2400,
    location: 'main_store',
    supplier: 'sup_002',
    batchNumber: null,
    expiryDate: null,
    lastRestocked: subDays(new Date(), 25),
    notes: 'Battery operated',
    isActive: true,
  },
  {
    id: 'inv_009',
    sku: 'CLN-DIS-001',
    name: 'Surface Disinfectant Spray',
    description: 'Hospital-grade surface disinfectant',
    category: 'cleaning',
    unit: 'bottle',
    quantity: 85,
    reorderLevel: 30,
    costPrice: 350,
    sellingPrice: 480,
    location: 'main_store',
    supplier: 'sup_005',
    batchNumber: 'BATCH-2024-018',
    expiryDate: addDays(new Date(), 365),
    lastRestocked: subDays(new Date(), 7),
    notes: '500ml per bottle',
    isActive: true,
  },
  {
    id: 'inv_010',
    sku: 'MED-CAN-001',
    name: 'IV Cannula (20G)',
    description: 'Sterile IV cannula with injection port',
    category: 'medical_supplies',
    unit: 'box',
    quantity: 12,
    reorderLevel: 25,
    costPrice: 580,
    sellingPrice: 750,
    location: 'icu_store',
    supplier: 'sup_001',
    batchNumber: 'BATCH-2024-025',
    expiryDate: addDays(new Date(), 180),
    lastRestocked: subDays(new Date(), 35),
    notes: '50 pcs per box',
    isActive: true,
  },
  {
    id: 'inv_011',
    sku: 'LAB-SLI-001',
    name: 'Microscope Slides',
    description: 'Plain glass microscope slides, ground edges',
    category: 'laboratory',
    unit: 'box',
    quantity: 28,
    reorderLevel: 15,
    costPrice: 180,
    sellingPrice: 280,
    location: 'lab_store',
    supplier: 'sup_004',
    batchNumber: null,
    expiryDate: null,
    lastRestocked: subDays(new Date(), 50),
    notes: '72 slides per box',
    isActive: true,
  },
  {
    id: 'inv_012',
    sku: 'SUR-SUT-001',
    name: 'Surgical Sutures (Silk 3-0)',
    description: 'Non-absorbable braided silk sutures',
    category: 'surgical',
    unit: 'box',
    quantity: 22,
    reorderLevel: 12,
    costPrice: 1200,
    sellingPrice: 1600,
    location: 'ot_store',
    supplier: 'sup_003',
    batchNumber: 'BATCH-2024-009',
    expiryDate: addDays(new Date(), 545),
    lastRestocked: subDays(new Date(), 40),
    notes: '12 packets per box',
    isActive: true,
  },
  {
    id: 'inv_013',
    sku: 'PPE-GWN-001',
    name: 'Disposable Surgical Gowns',
    description: 'Fluid-resistant disposable surgical gowns',
    category: 'ppe',
    unit: 'pack',
    quantity: 5,
    reorderLevel: 15,
    costPrice: 950,
    sellingPrice: 1250,
    location: 'ot_store',
    supplier: 'sup_005',
    batchNumber: 'BATCH-2024-028',
    expiryDate: addDays(new Date(), 730),
    lastRestocked: subDays(new Date(), 55),
    notes: '10 gowns per pack',
    isActive: true,
  },
  {
    id: 'inv_014',
    sku: 'EQP-OXI-001',
    name: 'Pulse Oximeter',
    description: 'Fingertip pulse oximeter with LED display',
    category: 'equipment',
    unit: 'piece',
    quantity: 40,
    reorderLevel: 15,
    costPrice: 800,
    sellingPrice: 1100,
    location: 'main_store',
    supplier: 'sup_002',
    batchNumber: null,
    expiryDate: null,
    lastRestocked: subDays(new Date(), 12),
    notes: 'Battery included',
    isActive: true,
  },
  {
    id: 'inv_015',
    sku: 'CON-GAU-001',
    name: 'Sterile Gauze Pads',
    description: 'Sterile gauze pads 4x4 inch',
    category: 'consumables',
    unit: 'pack',
    quantity: 95,
    reorderLevel: 40,
    costPrice: 120,
    sellingPrice: 180,
    location: 'ward_a',
    supplier: 'sup_001',
    batchNumber: 'BATCH-2024-020',
    expiryDate: addDays(new Date(), 545),
    lastRestocked: subDays(new Date(), 8),
    notes: '100 pads per pack',
    isActive: true,
  },
];

export const mockStockMovements = [
  {
    id: 'mov_001',
    itemId: 'inv_001',
    type: 'purchase',
    quantity: 100,
    previousQty: 50,
    newQty: 150,
    reference: 'PO-2024-0125',
    notes: 'Monthly restock',
    performedBy: 'Rahul Sharma',
    date: subDays(new Date(), 15),
  },
  {
    id: 'mov_002',
    itemId: 'inv_003',
    type: 'sale',
    quantity: 12,
    previousQty: 20,
    newQty: 8,
    reference: 'INV-2024-0892',
    notes: 'Dispensed to pharmacy',
    performedBy: 'Priya Patel',
    date: subDays(new Date(), 2),
  },
  {
    id: 'mov_003',
    itemId: 'inv_006',
    type: 'damage',
    quantity: 5,
    previousQty: 5,
    newQty: 0,
    reference: 'DMG-2024-0015',
    notes: 'Water damage in storage',
    performedBy: 'Vikram Singh',
    date: subDays(new Date(), 1),
  },
  {
    id: 'mov_004',
    itemId: 'inv_007',
    type: 'purchase',
    quantity: 50,
    previousQty: 70,
    newQty: 120,
    reference: 'PO-2024-0128',
    notes: 'Emergency restock',
    performedBy: 'Rahul Sharma',
    date: subDays(new Date(), 10),
  },
  {
    id: 'mov_005',
    itemId: 'inv_010',
    type: 'transfer_out',
    quantity: 8,
    previousQty: 20,
    newQty: 12,
    reference: 'TRF-2024-0042',
    notes: 'Transferred to Ward B',
    performedBy: 'Kavita Gupta',
    date: subDays(new Date(), 5),
  },
];
